In [1]:
from pulao.constant import SwingPoint
from vnpy.trader.constant import Exchange, Direction, Interval
from pulao.sbar import SBar,SBarManager
from vnpy.trader.object import BarData
import polars as pl

from pulao.swing import SwingManager

from IPython.display import display

df = pl.read_csv("../dataset/I8888.XDCE_60m.csv", try_parse_dates=True)
df = df.head(3)  # test

sbar_list = []
columns = df.columns

for idx, row in enumerate(df.iter_rows()):
    row_dict = dict(zip(columns, row))
    # datetime,open,close,high,low,volume,money,open_interest,signal
    datetime = row_dict["datetime"]
    open = row_dict["open"]
    close = row_dict["close"]
    high = row_dict["high"]
    low = row_dict["low"]
    volume = row_dict["volume"]
    money = row_dict["money"]
    open_interest = row_dict["open_interest"]

    bar = BarData(
        gateway_name="ctp-test",
        symbol="i8888",
        exchange=Exchange.SHFE,
        interval=Interval.MINUTE,
        datetime=datetime,
        open_price=open,
        close_price=close,
        high_price=high,
        low_price=low,
        volume=volume,
        open_interest=open_interest,
        turnover=money,
    )
    sbar = SBar(bar)
    sbar.swing_point = SwingPoint.HIGH if idx % 2 == 0 else SwingPoint.LOW

    #display(sbar.to_dict())
    sbar_list.append(sbar)
# 模拟行情数据接收
sbar_manager = SBarManager()
swing_manager = SwingManager(sbar_manager=sbar_manager)
for sbar in sbar_list:
    sbar_manager.append(sbar)

display(sbar_manager.df)
swing_manager.df

#row = sbar_manager.get_at_index(0)
#display(sbar_manager.df)

#sbar_manager.get_at_time(row["datetime"])
#sbar_manager.get_at_index(0)

shape: (3, 13)
┌────────────┬────────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ datetime   ┆ symbol ┆ exchange ┆ interval ┆ … ┆ open_inter ┆ swing_poin ┆ ema_20     ┆ ema_60    │
│ ---        ┆ ---    ┆ ---      ┆ ---      ┆   ┆ est        ┆ t          ┆ ---        ┆ ---       │
│ datetime[μ ┆ str    ┆ str      ┆ str      ┆   ┆ ---        ┆ ---        ┆ f32        ┆ f32       │
│ s]         ┆        ┆          ┆          ┆   ┆ f32        ┆ str        ┆            ┆           │
╞════════════╪════════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2024-01-22 ┆ i8888  ┆ SHFE     ┆ 1m       ┆ … ┆ 821104.0   ┆ high       ┆ 939.406982 ┆ 939.40698 │
│ 14:00:00   ┆        ┆          ┆          ┆   ┆            ┆            ┆            ┆ 2         │
│ 2024-01-22 ┆ i8888  ┆ SHFE     ┆ 1m       ┆ … ┆ 823890.0   ┆ low        ┆ 939.217102 ┆ 939.34161 │
│ 15:00:00   ┆        ┆          ┆          ┆   ┆            ┆            ┆            ┆ 4         │
│ 2024-01-22 ┆ i8888  ┆ SHFE     ┆ 1m       ┆ … ┆ 818145.0   ┆ high       ┆ 939.145264 ┆ 939.31280 │
│ 22:00:00   ┆        ┆          ┆          ┆   ┆            ┆            ┆            ┆ 5         │
└────────────┴────────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴───────────┘

shape: (1, 6)
┌─────────────────────┬────────┬──────────┬────────────┬────────────┬─────────────┐
│ datetime            ┆ symbol ┆ interval ┆ high_price ┆ low_price  ┆ swing_point │
│ ---                 ┆ ---    ┆ ---      ┆ ---        ┆ ---        ┆ ---         │
│ datetime[μs]        ┆ str    ┆ str      ┆ f32        ┆ f32        ┆ str         │
╞═════════════════════╪════════╪══════════╪════════════╪════════════╪═════════════╡
│ 2024-01-22 22:00:00 ┆ i8888  ┆ 1m       ┆ 942.234985 ┆ 928.388977 ┆             │
└─────────────────────┴────────┴──────────┴────────────┴────────────┴─────────────┘