In [1]:
from pulao.constant import SwingPointType
from vnpy.trader.constant import Exchange, Direction, Interval
from pulao.sbar import SBar,SBarManager
from vnpy.trader.object import BarData
import polars as pl

from pulao.swing import SwingManager

from IPython.display import display

df = pl.read_csv("../dataset/I8888.XDCE_60m.csv", try_parse_dates=True)
df = df.head(100)  # test

sbar_list = []
columns = df.columns

for idx, row in enumerate(df.iter_rows()):
    row_dict = dict(zip(columns, row))
    # datetime,open,close,high,low,volume,money,open_interest,signal
    datetime = row_dict["datetime"]
    open = row_dict["open"]
    close = row_dict["close"]
    high = row_dict["high"]
    low = row_dict["low"]
    volume = row_dict["volume"]
    money = row_dict["money"]
    open_interest = row_dict["open_interest"]

    bar = BarData(
        gateway_name="ctp-test",
        symbol="i8888",
        exchange=Exchange.SHFE,
        interval=Interval.MINUTE,
        datetime=datetime,
        open_price=open,
        close_price=close,
        high_price=high,
        low_price=low,
        volume=volume,
        open_interest=open_interest,
        turnover=money,
    )
    sbar = SBar(bar)

    #display(sbar.to_dict())
    sbar_list.append(sbar)
# 模拟行情数据接收
sbar_manager = SBarManager()
swing_manager = SwingManager(sbar_manager=sbar_manager)
for sbar in sbar_list:
    sbar_manager.append(sbar)

sbar_manager.df = sbar_manager.df.with_row_index()
display(sbar_manager.df)
swing_manager.df_cbar

#row = sbar_manager.get_at_index(0)
#display(sbar_manager.df)

shape: (100, 15)
┌───────┬─────────────┬────────┬──────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ index ┆ datetime    ┆ symbol ┆ exchange ┆ … ┆ swing_point ┆ swing_poin ┆ ema_20     ┆ ema_60     │
│ ---   ┆ ---         ┆ ---    ┆ ---      ┆   ┆ _type       ┆ t_level    ┆ ---        ┆ ---        │
│ u32   ┆ datetime[μs ┆ str    ┆ str      ┆   ┆ ---         ┆ ---        ┆ f32        ┆ f32        │
│       ┆ ]           ┆        ┆          ┆   ┆ str         ┆ i32        ┆            ┆            │
╞═══════╪═════════════╪════════╪══════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ 2024-01-22  ┆ i8888  ┆ SHFE     ┆ … ┆             ┆ 0          ┆ 939.406982 ┆ 939.406982 │
│       ┆ 14:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 1     ┆ 2024-01-22  ┆ i8888  ┆ SHFE     ┆ … ┆             ┆ 0          ┆ 939.217102 ┆ 939.341614 │
│       ┆ 15:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 2     ┆ 2024-01-22  ┆ i8888  ┆ SHFE     ┆ … ┆             ┆ 0          ┆ 939.145264 ┆ 939.312805 │
│       ┆ 22:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 3     ┆ 2024-01-22  ┆ i8888  ┆ SHFE     ┆ … ┆             ┆ 0          ┆ 940.123901 ┆ 939.644226 │
│       ┆ 23:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 4     ┆ 2024-01-23  ┆ i8888  ┆ SHFE     ┆ … ┆ high        ┆ 2          ┆ 941.34668  ┆ 940.080933 │
│       ┆ 10:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ …     ┆ …           ┆ …      ┆ …        ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 95    ┆ 2024-02-19  ┆ i8888  ┆ SHFE     ┆ … ┆ low         ┆ 1          ┆ 932.434998 ┆ 937.060608 │
│       ┆ 11:30:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 96    ┆ 2024-02-19  ┆ i8888  ┆ SHFE     ┆ … ┆             ┆ 0          ┆ 932.486023 ┆ 936.926514 │
│       ┆ 14:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 97    ┆ 2024-02-19  ┆ i8888  ┆ SHFE     ┆ … ┆ high        ┆ 1          ┆ 932.409058 ┆ 936.754456 │
│       ┆ 15:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 98    ┆ 2024-02-19  ┆ i8888  ┆ SHFE     ┆ … ┆             ┆ 0          ┆ 931.212524 ┆ 936.200012 │
│       ┆ 22:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
│ 99    ┆ 2024-02-19  ┆ i8888  ┆ SHFE     ┆ … ┆             ┆ 0          ┆ 930.24939  ┆ 935.704956 │
│       ┆ 23:00:00    ┆        ┆          ┆   ┆             ┆            ┆            ┆            │
└───────┴─────────────┴────────┴──────────┴───┴─────────────┴────────────┴────────────┴────────────┘

shape: (70, 6)
┌─────────────┬───────────┬────────────┬────────────┬──────────────────┬───────────────────┐
│ start_index ┆ end_index ┆ high_price ┆ low_price  ┆ swing_point_type ┆ swing_point_level │
│ ---         ┆ ---       ┆ ---        ┆ ---        ┆ ---              ┆ ---               │
│ i64         ┆ i64       ┆ f32        ┆ f32        ┆ str              ┆ i64               │
╞═════════════╪═══════════╪════════════╪════════════╪══════════════════╪═══════════════════╡
│ 0           ┆ 2         ┆ 942.234985 ┆ 928.388977 ┆                  ┆ 0                 │
│ 3           ┆ 3         ┆ 951.27301  ┆ 937.492981 ┆                  ┆ 0                 │
│ 4           ┆ 5         ┆ 955.56897  ┆ 947.655029 ┆ high             ┆ 2                 │
│ 6           ┆ 6         ┆ 950.607971 ┆ 946.338989 ┆ low              ┆ 1                 │
│ 7           ┆ 8         ┆ 953.411011 ┆ 948.630981 ┆                  ┆ 0                 │
│ …           ┆ …         ┆ …          ┆ …          ┆ …                ┆ …                 │
│ 94          ┆ 94        ┆ 943.085999 ┆ 933.172974 ┆                  ┆ 0                 │
│ 95          ┆ 95        ┆ 935.369995 ┆ 928.525024 ┆ low              ┆ 1                 │
│ 96          ┆ 96        ┆ 935.497986 ┆ 931.234985 ┆                  ┆ 0                 │
│ 97          ┆ 97        ┆ 939.71698  ┆ 931.296997 ┆ high             ┆ 1                 │
│ 98          ┆ 99        ┆ 932.031982 ┆ 917.692017 ┆                  ┆ 0                 │
└─────────────┴───────────┴────────────┴────────────┴──────────────────┴───────────────────┘