In [5]:
from collections import namedtuple
from time import sleep
import logging

from pulao.logging import init_logging

import pandas as pd

from pulao.trend import TrendManager
from pulao.swing import SwingManager
from pulao.bar import SBar, SBarManager, CBarManager
from vnpy.trader.constant import Exchange, Interval
from vnpy.trader.object import BarData

import polars as pl
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pulao.constant import *

from pulao.logging import logger
init_logging(level=logging.DEBUG)
open("./logs/pulao.log", "w").close() # 每次运行前清空日志
logger.debug("开始运行")

df = pl.read_csv("../dataset/I8888.XDCE_60m.csv", try_parse_dates=True)
df = df.head(100)  # test

sbar_list = []
columns = df.columns

for idx, row in enumerate(df.iter_rows()):
    row_dict = dict(zip(columns, row))
    # datetime,open,close,high,low,volume,money,open_interest,signal
    datetime = row_dict["datetime"]
    o = row_dict["open"]
    close = row_dict["close"]
    high = row_dict["high"]
    low = row_dict["low"]
    volume = row_dict["volume"]
    money = row_dict["money"]
    open_interest = row_dict["open_interest"]

    bar = BarData(
        gateway_name="ctp-test",
        symbol="i8888",
        exchange=Exchange.SHFE,
        interval=Interval.MINUTE,
        datetime=datetime,
        open_price=o,
        close_price=close,
        high_price=high,
        low_price=low,
        volume=volume,
        open_interest=open_interest,
        turnover=money,
    )
    sbar = SBar(symbol=bar.symbol, exchange=bar.exchange.value, interval=bar.interval.value, datetime=datetime, turnover=money, open_price=o, close_price=close, high_price=high, low_price=low, volume=volume)

    sbar_list.append(sbar)
# 模拟行情数据接收
sbar_manager = SBarManager()
cbar_manager = CBarManager(sbar_manager=sbar_manager)
swing_manager = SwingManager(cbar_manager=cbar_manager)

# 流入模拟数据
for sbar in sbar_list:
    sbar_manager.append(sbar)

logger.debug("运行结束")
# sleep(3) # 等一会，让日志输出完
#
# region . Plotly - Cbar
#
df_cbar = cbar_manager.df_cbar.to_pandas()
df_cbar["datetime"] = pd.date_range("2025-01-01", periods=df_cbar.shape[0], freq="h")
df_cbar["open_price"] = df_cbar["high_price"]
df_cbar["close_price"] = df_cbar["low_price"]
df_cbar.insert(0, "index", range(len(df_cbar)))

# region 构建波段数据
df_swing = swing_manager.df_swing.to_pandas()
df_swing["start_datetime"] = pd.Series(dtype="datetime64[ns]")
df_swing["end_datetime"] = pd.Series(dtype="datetime64[ns]")
df_swing.insert(0, "index", range(len(df_swing)))

for i, row in enumerate(df_swing.itertuples()):
    df = df_cbar[(df_cbar["id"] >= row.cbar_start_id) & (df_cbar["id"] <= row.cbar_end_id)]
    start_datetime = df.iloc[0]["datetime"]
    end_datetime = df.iloc[-1]["datetime"]
    df_swing.at[i, "start_datetime"] = start_datetime
    df_swing.at[i, "end_datetime"] = end_datetime

xs = []
ys = []
texts = []
text_positions  = []
for i, row in enumerate(df_swing.itertuples()):
    xs += [row.start_datetime, row.end_datetime, None]
    start_index = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["index"].iloc[0]
    end_index = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["index"].iloc[0]
    if row.direction == Direction.UP:
        start_price = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["low_price"].iloc[0]
        end_price = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["high_price"].iloc[0]
        text_positions += ['bottom center', 'top center', "middle center"]
    else:
        start_price = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["high_price"].iloc[0]
        end_price = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["low_price"].iloc[0]
        text_positions += ['top center', 'bottom center', "middle center"]
    ys += [start_price, end_price, None]
    texts += [start_index, end_index, None]


# endregion

fig = make_subplots(
    rows=1, cols=1
)
fig.add_trace(go.Candlestick(
    x=df_cbar['datetime'],
    open=df_cbar['open_price'],
    high=df_cbar['high_price'],
    low=df_cbar['low_price'],
    close=df_cbar['close_price'],
    name='K线',
), row=1, col=1)

df_fractal_bottom = df_cbar[(df_cbar['fractal_type'] == FractalType.BOTTOM)]

fig.add_trace(go.Scatter(
    x=df_fractal_bottom['datetime'],
    y=df_fractal_bottom['low_price'] * 0.995,   # 放在K线最低价下方一点，不遮挡蜡烛
    mode='markers+text',
    name='swing point low',
    marker=dict(
        symbol='triangle-up',
        size=14,
        color='#1E90FF',
    ),
    text=df_fractal_bottom["index"],      # ← 添加序号
    textposition="bottom center",              # ← 文字位置
    textfont=dict(size=10, color="white"),
    hovertemplate=
        "<b>波段低点</b><br>" +
        "时间: %{x}<br>" +
        "价格: %{y:.2f}<br>" +
        "<extra></extra>"
), row=1, col=1)


df_fractal_top = df_cbar[(df_cbar['fractal_type'] == FractalType.TOP)]

fig.add_trace(go.Scatter(
    x=df_fractal_top['datetime'],
    y=df_fractal_top['high_price'] * 1.005,  # 放在K线最高价上方一点
    mode='markers+text',
    name='swing point high',
    marker=dict(
        symbol='triangle-down',
        size=14,
        color='#FF4500',
    ),
    text=df_fractal_top["index"],      # ← 添加序号
    textposition="top center",              # ← 文字位置
    textfont=dict(size=10, color="white"),
    hovertemplate=
        "<b>波段高点</b><br>" +
        "时间: %{x}<br>" +
        "价格: %{y:.2f}<br>" +
        "<extra></extra>"
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=xs,
    y=ys,
    name='swing segments',
    mode='lines+text',    # lines+text 支持显示文字
    line=dict(width=2, color='orange'),
    text=texts,
    textposition=text_positions,  # 文字位置
))

title = 'Swing Chart - 波段标识'
fig.update_layout(title=title,
                  height=900,
                  hovermode='x unified',  # X轴悬停联动虚线
                  )

fig.update_xaxes(
    showgrid=False,
)

fig.update_yaxes(
    showgrid=False,
)

fig.show()

# endregion

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"cbar_count": 1, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"cbar_count": 1, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"cbar_count": 2, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"fractal": "Fractal(left=CBar(id=120122780241887232, start_id=120122780225110016, end_id=120122780237692928, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 583000), fractal_type=0), middle=CBar(id=120122780254470144, start_id=120122780250275840, end_id=120122780250275840, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 586000), fractal_type=-1), right=CBar(id=120122780267053056, start_id=120122780262858752, end_id=120122780262858752, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 589000), fractal_type=0))", "event": "首次波段创建", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"event": "_valid_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"event": "_valid_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"start_fractal": "Fractal(left=CBar(id=120122780241887232, start_id=120122780225110016, end_id=120122780237692928, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 583000), fractal_type=0), middle=CBar(id=120122780254470144, start_id=120122780250275840, end_id=120122780250275840, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 586000), fractal_type=-1), right=CBar(id=120122780267053056, start_id=120122780262858752, end_id=120122780262858752, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 589000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120122780418048000, start_id=120122780418048000, end_id=120122780418048000, high_price=974.1920166015625, low_price=967.3179931640625, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 625000), fractal_type=0), middle=CBar(id=120122780434825216, start_id=120122780434825216, end_id=120122780434825216, high_price=980.2589721679688, low_price=972.8519897460938, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 629000), fractal_type=1), right=CBar(id=120122780447408128, start_id=120122780443213824, end_id=120122780443213824, high_price=979.760009765625, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 632000), fractal_type=0))", "active_swing": "Swing(id=120122780443213824, direction=1, start_id=120122780254470144, end_id=120122780434825216, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 631000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=120122780443213824, direction=1, start_id=120122780254470144, end_id=120122780434825216, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 631000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=None, direction=-1, start_id=120122780434825216, end_id=120122780464185344, high_price=980.2589721679688, low_price=967.3179931640625, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120122780455796736, direction=1, start_id=120122780254470144, end_id=120122780434825216, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 634000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"last_completed_swing": "Swing(id=120122780455796736, direction=1, start_id=120122780254470144, end_id=120122780480962560, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 634000))", "last_bar": "CBar(id=120122780480962560, start_id=120122780476768256, end_id=120122780476768256, high_price=982.2230224609375, low_price=976.85302734375, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 640000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"start_fractal": "Fractal(left=CBar(id=120122780241887232, start_id=120122780225110016, end_id=120122780237692928, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 583000), fractal_type=0), middle=CBar(id=120122780254470144, start_id=120122780250275840, end_id=120122780250275840, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 586000), fractal_type=-1), right=CBar(id=120122780267053056, start_id=120122780262858752, end_id=120122780262858752, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 589000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120122780464185344, start_id=120122780443213824, end_id=120122780459991040, high_price=979.7579956054688, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 636000), fractal_type=-1), middle=CBar(id=120122780497739776, start_id=120122780476768256, end_id=120122780497739776, high_price=982.2230224609375, low_price=977.7880249023438, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 644000), fractal_type=1), right=CBar(id=120122780510322688, start_id=120122780510322688, end_id=120122780510322688, high_price=981.0230102539062, low_price=971.3280029296875, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 647000), fractal_type=0))", "active_swing": "Swing(id=120122780510322688, direction=1, start_id=120122780254470144, end_id=120122780497739776, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 647000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=120122780510322688, direction=1, start_id=120122780254470144, end_id=120122780497739776, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 647000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=None, direction=-1, start_id=120122780497739776, end_id=120122780527099904, high_price=982.2230224609375, low_price=971.3280029296875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120122780518711296, direction=1, start_id=120122780254470144, end_id=120122780497739776, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 649000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"last_completed_swing": "Swing(id=120122780518711296, direction=1, start_id=120122780254470144, end_id=120122780652929024, high_price=982.3079833984375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 649000))", "last_bar": "CBar(id=120122780652929024, start_id=120122780652929024, end_id=120122780652929024, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 681000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"start_fractal": "Fractal(left=CBar(id=120122780241887232, start_id=120122780225110016, end_id=120122780237692928, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 583000), fractal_type=0), middle=CBar(id=120122780254470144, start_id=120122780250275840, end_id=120122780250275840, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 586000), fractal_type=-1), right=CBar(id=120122780267053056, start_id=120122780262858752, end_id=120122780262858752, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 589000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120122780652929024, start_id=120122780652929024, end_id=120122780652929024, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 681000), fractal_type=0), middle=CBar(id=120122780703260672, start_id=120122780665511936, end_id=120122780699066368, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 693000), fractal_type=1), right=CBar(id=120122780707454976, start_id=120122780707454976, end_id=120122780707454976, high_price=984.6690063476562, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 694000), fractal_type=0))", "active_swing": "Swing(id=120122780707454976, direction=1, start_id=120122780254470144, end_id=120122780703260672, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 694000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=120122780707454976, direction=1, start_id=120122780254470144, end_id=120122780703260672, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 694000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=None, direction=-1, start_id=120122780703260672, end_id=120122780720037888, high_price=988.5280151367188, low_price=972.7020263671875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120122780715843584, direction=1, start_id=120122780254470144, end_id=120122780703260672, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 696000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"start_fractal": "Fractal(left=CBar(id=120122780652929024, start_id=120122780652929024, end_id=120122780652929024, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 681000), fractal_type=0), middle=CBar(id=120122780703260672, start_id=120122780665511936, end_id=120122780699066368, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 693000), fractal_type=1), right=CBar(id=120122780720037888, start_id=120122780707454976, end_id=120122780720037888, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 697000), fractal_type=-1))", "end_fractal": "Fractal(left=CBar(id=120122780812312576, start_id=120122780812312576, end_id=120122780812312576, high_price=965.2780151367188, low_price=952.3099975585938, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 719000), fractal_type=0), middle=CBar(id=120122780841672704, start_id=120122780824895488, end_id=120122780837478400, high_price=957.35498046875, low_price=948.010009765625, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 726000), fractal_type=-1), right=CBar(id=120122780850061312, start_id=120122780845867008, end_id=120122780845867008, high_price=959.2680053710938, low_price=952.9249877929688, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 728000), fractal_type=0))", "active_swing": "Swing(id=120122780845867008, direction=-1, start_id=120122780703260672, end_id=120122780841672704, high_price=988.5280151367188, low_price=948.010009765625, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 727000))", "prev_swing": "Swing(id=120122780715843584, direction=1, start_id=120122780254470144, end_id=120122780703260672, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 696000))", "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=120122780845867008, direction=-1, start_id=120122780703260672, end_id=120122780841672704, high_price=988.5280151367188, low_price=948.010009765625, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 727000))", "prev_swing": "Swing(id=120122780715843584, direction=1, start_id=120122780254470144, end_id=120122780703260672, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 696000))", "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=None, direction=1, start_id=120122780841672704, end_id=120122780850061312, high_price=965.2780151367188, low_price=948.010009765625, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120122780858449920, direction=-1, start_id=120122780703260672, end_id=120122780841672704, high_price=988.5280151367188, low_price=948.010009765625, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 730000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"last_completed_swing": "Swing(id=120122780858449920, direction=-1, start_id=120122780703260672, end_id=120122780892004352, high_price=988.5280151367188, low_price=943.6160278320312, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 730000))", "last_bar": "CBar(id=120122780892004352, start_id=120122780858449920, end_id=120122780883615744, high_price=955.2860107421875, low_price=943.6160278320312, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 738000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"start_fractal": "Fractal(left=CBar(id=120122780652929024, start_id=120122780652929024, end_id=120122780652929024, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 681000), fractal_type=0), middle=CBar(id=120122780703260672, start_id=120122780665511936, end_id=120122780699066368, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 693000), fractal_type=1), right=CBar(id=120122780720037888, start_id=120122780707454976, end_id=120122780720037888, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 697000), fractal_type=-1))", "end_fractal": "Fractal(left=CBar(id=120122780892004352, start_id=120122780858449920, end_id=120122780883615744, high_price=955.2860107421875, low_price=943.6160278320312, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 738000), fractal_type=0), middle=CBar(id=120122780904587264, start_id=120122780900392960, end_id=120122780900392960, high_price=945.0120239257812, low_price=937.1669921875, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 741000), fractal_type=-1), right=CBar(id=120122780912975872, start_id=120122780912975872, end_id=120122780912975872, high_price=952.7420043945312, low_price=940.0430297851562, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 743000), fractal_type=0))", "active_swing": "Swing(id=120122780912975872, direction=-1, start_id=120122780703260672, end_id=120122780904587264, high_price=988.5280151367188, low_price=937.1669921875, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 743000))", "prev_swing": "Swing(id=120122780715843584, direction=1, start_id=120122780254470144, end_id=120122780703260672, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 696000))", "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=120122780912975872, direction=-1, start_id=120122780703260672, end_id=120122780904587264, high_price=988.5280151367188, low_price=937.1669921875, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 743000))", "prev_swing": "Swing(id=120122780715843584, direction=1, start_id=120122780254470144, end_id=120122780703260672, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 696000))", "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"active_swing": "Swing(id=None, direction=1, start_id=120122780904587264, end_id=120122780925558784, high_price=955.2860107421875, low_price=937.1669921875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120122780921364480, direction=-1, start_id=120122780703260672, end_id=120122780904587264, high_price=988.5280151367188, low_price=937.1669921875, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 745000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}
{"last_completed_swing": "Swing(id=120122780921364480, direction=-1, start_id=120122780703260672, end_id=120122780992667648, high_price=988.5280151367188, low_price=933.6090087890625, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 745000))", "last_bar": "CBar(id=120122780992667648, start_id=120122780992667648, end_id=120122780992667648, high_price=942.8469848632812, low_price=933.6090087890625, created_at=datetime.datetime(2025, 11, 28, 11, 25, 2, 762000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 11:25:02"}

In [4]:
# 测试swing 构建算法
from IPython.display import display
from pulao.logging import logger,init_logging
import logging
from time import sleep
from pulao.swing import Swing,SwingManager
from pulao.bar import CBar,CBarManager,SBarManager
from pulao.constant import EventType
init_logging(level=logging.DEBUG)
with open("./logs/pulao.log", "w"):
    pass # 每次运行前清空日志

logger.debug("开始运行")

def format_df_swing():
    # 在df_swing中显示df_cbar的索引顺序
    import polars as pl
    if "index" in cbar_manager.df_cbar.columns:
        cbar_manager.df_cbar = cbar_manager.df_cbar.drop("index")
    cbar_manager.df_cbar = cbar_manager.df_cbar.with_row_index("index")

    df_cbar = cbar_manager.df_cbar.select(["id","index"])
    df1 = swing_manager.df_swing.join(df_cbar, left_on="start_id", right_on="id", how="left")
    df2 = swing_manager.df_swing.join(df_cbar, left_on="end_id", right_on="id", how="left")
    df1 = df1.rename({"index":"start_index"})
    df2 = df2.rename({"index":"end_index"})
    df2 = df2.select(["id","end_index"])
    df1 = df1.join(df2, on="id", how="left")
    df = df1.select(["id","start_index","end_index","start_id","end_id","high_price","low_price","direction","is_completed","created_at"])

    return df


cbar_manager = CBarManager(sbar_manager=SBarManager())
swing_manager = SwingManager(cbar_manager=cbar_manager)
df_cbar = cbar_manager.read_parquet()
cbar_manager.df_cbar = cbar_manager.df_cbar.slice(0,0)
for i in range(df_cbar.height-1):
    cbar = CBar(**df_cbar.row(i, named=True))
    cbar_manager._append_cbar(start_id=cbar.sbar_start_id, end_id=cbar.sbar_end_id, high_price=cbar.high_price, low_price=cbar.low_price, fractal_type=cbar.fractal_type)
    cbar_manager.notify(EventType.CBAR_CREATED)

logger.debug("运行结束")
sleep(0.2)


display("df_swing")
df = format_df_swing()
display(df)

display("df_cbar")
cbar_manager.df_cbar

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"cbar_count": 1, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"cbar_count": 2, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"fractal": "Fractal(left=CBar(id=120070865390927872, start_id=120070369473200128, end_id=120070369502560256, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 118000), fractal_type=0), middle=CBar(id=120070865395122176, start_id=120070369523531776, end_id=120070369523531776, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=-1), right=CBar(id=120070865395122177, start_id=120070369548697600, end_id=120070369548697600, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=0))", "event": "首次波段创建", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"event": "_valid_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"event": "_valid_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"start_fractal": "Fractal(left=CBar(id=120070865390927872, start_id=120070369473200128, end_id=120070369502560256, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 118000), fractal_type=0), middle=CBar(id=120070865395122176, start_id=120070369523531776, end_id=120070369523531776, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=-1), right=CBar(id=120070865395122177, start_id=120070369548697600, end_id=120070369548697600, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120070865504174080, start_id=120070369804550144, end_id=120070369804550144, high_price=974.1920166015625, low_price=967.3179931640625, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 145000), fractal_type=0), middle=CBar(id=120070865508368384, start_id=120070369817133056, end_id=120070369817133056, high_price=980.2589721679688, low_price=972.8519897460938, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 146000), fractal_type=1), right=CBar(id=120070865512562688, start_id=120070369829715968, end_id=120070369863270400, high_price=979.7579956054688, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 147000), fractal_type=-1))", "active_swing": "Swing(id=120070865512562688, direction=1, start_id=120070865395122176, end_id=120070865508368384, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 147000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=120070865512562688, direction=1, start_id=120070865395122176, end_id=120070865508368384, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 147000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"last_completed_swing": "Swing(id=120070865516756992, direction=1, start_id=120070865395122176, end_id=120070865525145600, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 148000))", "last_bar": "CBar(id=120070865525145600, start_id=120070369888436224, end_id=120070369926184960, high_price=982.2230224609375, low_price=977.7880249023438, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 150000), fractal_type=1)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"start_fractal": "Fractal(left=CBar(id=120070865390927872, start_id=120070369473200128, end_id=120070369502560256, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 118000), fractal_type=0), middle=CBar(id=120070865395122176, start_id=120070369523531776, end_id=120070369523531776, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=-1), right=CBar(id=120070865395122177, start_id=120070369548697600, end_id=120070369548697600, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120070865512562688, start_id=120070369829715968, end_id=120070369863270400, high_price=979.7579956054688, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 147000), fractal_type=-1), middle=CBar(id=120070865525145600, start_id=120070369888436224, end_id=120070369926184960, high_price=982.2230224609375, low_price=977.7880249023438, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 150000), fractal_type=1), right=CBar(id=120070865533534208, start_id=120070369942962176, end_id=120070369959739392, high_price=978.1209716796875, low_price=971.3280029296875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 152000), fractal_type=0))", "active_swing": "Swing(id=120070865529339904, direction=1, start_id=120070865395122176, end_id=120070865525145600, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 151000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=120070865529339904, direction=1, start_id=120070865395122176, end_id=120070865525145600, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 151000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=None, direction=-1, start_id=120070865525145600, end_id=120070865533534208, high_price=982.2230224609375, low_price=971.3280029296875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120070865541922816, direction=1, start_id=120070865395122176, end_id=120070865525145600, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 154000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"last_completed_swing": "Swing(id=120070865541922816, direction=1, start_id=120070865395122176, end_id=120070865609031680, high_price=982.3079833984375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 154000))", "last_bar": "CBar(id=120070865609031680, start_id=120070370106540032, end_id=120070370106540032, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"start_fractal": "Fractal(left=CBar(id=120070865390927872, start_id=120070369473200128, end_id=120070369502560256, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 118000), fractal_type=0), middle=CBar(id=120070865395122176, start_id=120070369523531776, end_id=120070369523531776, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=-1), right=CBar(id=120070865395122177, start_id=120070369548697600, end_id=120070369548697600, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 119000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120070865609031680, start_id=120070370106540032, end_id=120070370106540032, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=0), middle=CBar(id=120070865609031681, start_id=120070370135900160, end_id=120070370169454592, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=1), right=CBar(id=120070865617420288, start_id=120070370177843200, end_id=120070370198814720, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 172000), fractal_type=-1))", "active_swing": "Swing(id=120070865617420288, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 172000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=120070865617420288, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 172000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=None, direction=-1, start_id=120070865609031681, end_id=120070865617420288, high_price=988.5280151367188, low_price=972.7020263671875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120070865621614592, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 173000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"start_fractal": "Fractal(left=CBar(id=120070865609031680, start_id=120070370106540032, end_id=120070370106540032, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=0), middle=CBar(id=120070865609031681, start_id=120070370135900160, end_id=120070370169454592, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=1), right=CBar(id=120070865617420288, start_id=120070370177843200, end_id=120070370198814720, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 172000), fractal_type=-1))", "end_fractal": "Fractal(left=CBar(id=120070865671946240, start_id=120070370337226752, end_id=120070370337226752, high_price=965.2780151367188, low_price=952.3099975585938, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 185000), fractal_type=0), middle=CBar(id=120070865676140544, start_id=120070370349809664, end_id=120070370362392576, high_price=957.35498046875, low_price=948.010009765625, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 186000), fractal_type=-1), right=CBar(id=120070865680334848, start_id=120070370370781184, end_id=120070370370781184, high_price=959.2680053710938, low_price=952.9249877929688, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 187000), fractal_type=1))", "active_swing": "Swing(id=120070865680334848, direction=-1, start_id=120070865609031681, end_id=120070865676140544, high_price=988.5280151367188, low_price=948.010009765625, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 187000))", "prev_swing": "Swing(id=120070865621614592, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 173000))", "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=120070865680334848, direction=-1, start_id=120070865609031681, end_id=120070865676140544, high_price=988.5280151367188, low_price=948.010009765625, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 187000))", "prev_swing": "Swing(id=120070865621614592, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 173000))", "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"last_completed_swing": "Swing(id=120070865684529152, direction=-1, start_id=120070865609031681, end_id=120070865688723456, high_price=988.5280151367188, low_price=943.6160278320312, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 188000))", "last_bar": "CBar(id=120070865688723456, start_id=120070370433695744, end_id=120070370458861568, high_price=955.2860107421875, low_price=943.6160278320312, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 189000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"start_fractal": "Fractal(left=CBar(id=120070865609031680, start_id=120070370106540032, end_id=120070370106540032, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=0), middle=CBar(id=120070865609031681, start_id=120070370135900160, end_id=120070370169454592, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=1), right=CBar(id=120070865617420288, start_id=120070370177843200, end_id=120070370198814720, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 172000), fractal_type=-1))", "end_fractal": "Fractal(left=CBar(id=120070865688723456, start_id=120070370433695744, end_id=120070370458861568, high_price=955.2860107421875, low_price=943.6160278320312, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 189000), fractal_type=0), middle=CBar(id=120070865692917760, start_id=120070370496610304, end_id=120070370496610304, high_price=945.0120239257812, low_price=937.1669921875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 190000), fractal_type=-1), right=CBar(id=120070865709694976, start_id=120070370513387520, end_id=120070370525970432, high_price=952.7420043945312, low_price=943.9140014648438, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 194000), fractal_type=0))", "active_swing": "Swing(id=120070865709694976, direction=-1, start_id=120070865609031681, end_id=120070865692917760, high_price=988.5280151367188, low_price=937.1669921875, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 194000))", "prev_swing": "Swing(id=120070865621614592, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 173000))", "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=120070865709694976, direction=-1, start_id=120070865609031681, end_id=120070865692917760, high_price=988.5280151367188, low_price=937.1669921875, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 194000))", "prev_swing": "Swing(id=120070865621614592, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 173000))", "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"active_swing": "Swing(id=None, direction=1, start_id=120070865692917760, end_id=120070865709694976, high_price=955.2860107421875, low_price=937.1669921875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=120070865718083584, direction=-1, start_id=120070865609031681, end_id=120070865692917760, high_price=988.5280151367188, low_price=937.1669921875, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 196000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"last_completed_swing": "Swing(id=120070865718083584, direction=-1, start_id=120070865609031681, end_id=120070865772609536, high_price=988.5280151367188, low_price=933.6090087890625, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 196000))", "last_bar": "CBar(id=120070865772609536, start_id=120070370668576768, end_id=120070370668576768, high_price=942.8469848632812, low_price=933.6090087890625, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 209000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}
{"start_fractal": "Fractal(left=CBar(id=120070865609031680, start_id=120070370106540032, end_id=120070370106540032, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=0), middle=CBar(id=120070865609031681, start_id=120070370135900160, end_id=120070370169454592, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 170000), fractal_type=1), right=CBar(id=120070865617420288, start_id=120070370177843200, end_id=120070370198814720, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 172000), fractal_type=-1))", "end_fractal": "Fractal(left=CBar(id=120070865789386752, start_id=120070370760851456, end_id=120070370760851456, high_price=927.7100219726562, low_price=920.7349853515625, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 213000), fractal_type=0), middle=CBar(id=120070865793581056, start_id=120070370769240064, end_id=120070370769240064, high_price=923.343994140625, low_price=918.0250244140625, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 214000), fractal_type=-1), right=CBar(id=120070865806163968, start_id=120070370786017280, end_id=120070370786017280, high_price=931.2930297851562, low_price=918.4520263671875, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 217000), fractal_type=1))", "active_swing": "Swing(id=120070865801969664, direction=-1, start_id=120070865609031681, end_id=120070865793581056, high_price=988.5280151367188, low_price=918.0250244140625, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 216000))", "prev_swing": "Swing(id=120070865621614592, direction=1, start_id=120070865395122176, end_id=120070865609031681, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 7, 58, 45, 173000))", "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 07:58:45"}

'df_swing'

shape: (33, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ start_ind ┆ end_index ┆ start_id  ┆ … ┆ low_price ┆ direction ┆ is_comple ┆ created_ │
│ ---       ┆ ex        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ted       ┆ at       │
│ u64       ┆ ---       ┆ u32       ┆ u64       ┆   ┆ f32       ┆ i8        ┆ ---       ┆ ---      │
│           ┆ u32       ┆           ┆           ┆   ┆           ┆           ┆ bool      ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [ms]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 120070865 ┆ 1         ┆ 24        ┆ 120070865 ┆ … ┆ 930.29797 ┆ 1         ┆ true      ┆ 2025-11- │
│ 621614592 ┆           ┆           ┆ 395122176 ┆   ┆ 4         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :45.173  │
│ 120070865 ┆ 24        ┆ 52        ┆ 120070865 ┆ … ┆ 906.14300 ┆ -1        ┆ true      ┆ 2025-11- │
│ 890050048 ┆           ┆           ┆ 609031681 ┆   ┆ 5         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :45.237  │
│ 120070865 ┆ 52        ┆ 67        ┆ 120070865 ┆ … ┆ 906.14300 ┆ 1         ┆ true      ┆ 2025-11- │
│ 978130433 ┆           ┆           ┆ 881661440 ┆   ┆ 5         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :45.258  │
│ 120070866 ┆ 67        ┆ 98        ┆ 120070865 ┆ … ┆ 842.13397 ┆ -1        ┆ true      ┆ 2025-11- │
│ 154291200 ┆           ┆           ┆ 973936129 ┆   ┆ 2         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :45.300  │
│ 120070866 ┆ 98        ┆ 104       ┆ 120070866 ┆ … ┆ 842.13397 ┆ 1         ┆ true      ┆ 2025-11- │
│ 196234240 ┆           ┆           ┆ 137513985 ┆   ┆ 2         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :45.310  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 120070871 ┆ 635       ┆ 641       ┆ 120070871 ┆ … ┆ 752.09802 ┆ 1         ┆ true      ┆ 2025-11- │
│ 317479424 ┆           ┆           ┆ 191650304 ┆   ┆ 2         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :46.531  │
│ 120070871 ┆ 641       ┆ 653       ┆ 120070871 ┆ … ┆ 739.61102 ┆ -1        ┆ true      ┆ 2025-11- │
│ 439114240 ┆           ┆           ┆ 271342080 ┆   ┆ 3         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :46.560  │
│ 120070871 ┆ 653       ┆ 672       ┆ 120070871 ┆ … ┆ 739.61102 ┆ 1         ┆ true      ┆ 2025-11- │
│ 627857920 ┆           ┆           ┆ 426531328 ┆   ┆ 3         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :46.605  │
│ 120070872 ┆ 672       ┆ 722       ┆ 120070871 ┆ … ┆ 690.55999 ┆ -1        ┆ true      ┆ 2025-11- │
│ 114397184 ┆           ┆           ┆ 611080704 ┆   ┆ 8         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :46.721  │
│ 120070872 ┆ 722       ┆ 758       ┆ 120070872 ┆ … ┆ 690.55999 ┆ 1         ┆ false     ┆ 2025-11- │
│ 558993408 ┆           ┆           ┆ 093425664 ┆   ┆ 8         ┆           ┆           ┆ 28 07:58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :46.827  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

'df_cbar'

shape: (759, 8)
┌───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ id         ┆ start_id   ┆ end_id     ┆ high_price ┆ low_price  ┆ fractal_ty ┆ created_at │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ pe         ┆ ---        │
│ u32   ┆ u64        ┆ u64        ┆ u64        ┆ f32        ┆ f32        ┆ ---        ┆ datetime[m │
│       ┆            ┆            ┆            ┆            ┆            ┆ i8         ┆ s]         │
╞═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ 1200708653 ┆ 1200703694 ┆ 1200703695 ┆ 942.234985 ┆ 935.924011 ┆ 0          ┆ 2025-11-28 │
│       ┆ 90927872   ┆ 73200128   ┆ 02560256   ┆            ┆            ┆            ┆ 07:58:45.1 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 18         │
│ 1     ┆ 1200708653 ┆ 1200703695 ┆ 1200703695 ┆ 939.052002 ┆ 930.297974 ┆ -1         ┆ 2025-11-28 │
│       ┆ 95122176   ┆ 23531776   ┆ 23531776   ┆            ┆            ┆            ┆ 07:58:45.1 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 19         │
│ 2     ┆ 1200708653 ┆ 1200703695 ┆ 1200703695 ┆ 951.27301  ┆ 937.492981 ┆ 0          ┆ 2025-11-28 │
│       ┆ 95122177   ┆ 48697600   ┆ 48697600   ┆            ┆            ┆            ┆ 07:58:45.1 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 19         │
│ 3     ┆ 1200708653 ┆ 1200703696 ┆ 1200703696 ┆ 955.56897  ┆ 948.888    ┆ 1          ┆ 2025-11-28 │
│       ┆ 99316480   ┆ 20000768   ┆ 45166592   ┆            ┆            ┆            ┆ 07:58:45.1 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 20         │
│ 4     ┆ 1200708654 ┆ 1200703696 ┆ 1200703696 ┆ 950.607971 ┆ 946.338989 ┆ -1         ┆ 2025-11-28 │
│       ┆ 03510784   ┆ 57749504   ┆ 57749504   ┆            ┆            ┆            ┆ 07:58:45.1 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 21         │
│ …     ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 754   ┆ 1200708725 ┆ 1200703900 ┆ 1200703900 ┆ 740.593994 ┆ 730.604004 ┆ 0          ┆ 2025-11-28 │
│       ┆ 33827584   ┆ 12706816   ┆ 12706816   ┆            ┆            ┆            ┆ 07:58:46.8 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 21         │
│ 755   ┆ 1200708725 ┆ 1200703900 ┆ 1200703900 ┆ 741.554016 ┆ 735.406982 ┆ 0          ┆ 2025-11-28 │
│       ┆ 38021888   ┆ 46261248   ┆ 67232768   ┆            ┆            ┆            ┆ 07:58:46.8 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 22         │
│ 756   ┆ 1200708725 ┆ 1200703900 ┆ 1200703900 ┆ 747.684021 ┆ 740.830994 ┆ 0          ┆ 2025-11-28 │
│       ┆ 42216192   ┆ 84009984   ┆ 84009984   ┆            ┆            ┆            ┆ 07:58:46.8 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 23         │
│ 757   ┆ 1200708725 ┆ 1200703901 ┆ 1200703901 ┆ 751.919006 ┆ 744.698975 ┆ 0          ┆ 2025-11-28 │
│       ┆ 46410496   ┆ 00787200   ┆ 00787200   ┆            ┆            ┆            ┆ 07:58:46.8 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 24         │
│ 758   ┆ 1200708725 ┆ 1200703901 ┆ 1200703901 ┆ 756.898987 ┆ 752.330994 ┆ 0          ┆ 2025-11-28 │
│       ┆ 54799104   ┆ 25953024   ┆ 97256192   ┆            ┆            ┆            ┆ 07:58:46.8 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 26         │
└───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
# 可视化日志
import pandas as pd
df = pd.read_json("./logs/pulao.log",lines=True)
df = df.drop(columns=["logger","level","time"])
priority_cols = ["event"]
other_cols = [c for c in df.columns if c not in priority_cols]
df = df[priority_cols+other_cols]
df["info"] = df[other_cols].apply(lambda row: row.dropna().tolist(), axis=1)
df = df.drop(columns=other_cols)
df["info"] = df["info"].apply(lambda x: "" if x == [] else x)
df

In [14]:
df = sbar_manager.df_sbar
df = df.with_columns(
    pl.concat_list(["ema_short","ema_long"]).alias("ema")
)
df.lazy().select(pl.col("ema")).explain()

'DF ["id", "datetime", "symbol", "exchange", ...]; PROJECT["ema"] 1/15 COLUMNS'