In [3]:
from collections import namedtuple
from time import sleep
import logging

from pulao.logging import init_logging

import pandas as pd

from pulao.trend import TrendManager
from pulao.swing import SwingManager
from pulao.bar import SBar, SBarManager, CBarManager
from vnpy.trader.constant import Exchange, Interval
from vnpy.trader.object import BarData

import polars as pl
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pulao.constant import *

from pulao.logging import logger
init_logging(level=logging.DEBUG)
open("./logs/pulao.log", "w").close() # 每次运行前清空日志
logger.debug("开始运行")

df = pl.read_csv("../dataset/I8888.XDCE_60m.csv", try_parse_dates=True)
df = df.head(100*3)  # test

sbar_list = []
columns = df.columns

for idx, row in enumerate(df.iter_rows()):
    row_dict = dict(zip(columns, row))
    # datetime,open,close,high,low,volume,money,open_interest,signal
    datetime = row_dict["datetime"]
    o = row_dict["open"]
    close = row_dict["close"]
    high = row_dict["high"]
    low = row_dict["low"]
    volume = row_dict["volume"]
    money = row_dict["money"]
    open_interest = row_dict["open_interest"]

    bar = BarData(
        gateway_name="ctp-test",
        symbol="i8888",
        exchange=Exchange.SHFE,
        interval=Interval.MINUTE,
        datetime=datetime,
        open_price=o,
        close_price=close,
        high_price=high,
        low_price=low,
        volume=volume,
        open_interest=open_interest,
        turnover=money,
    )
    sbar = SBar(symbol=bar.symbol, exchange=bar.exchange.value, interval=bar.interval.value, datetime=datetime, turnover=money, open_price=o, close_price=close, high_price=high, low_price=low, volume=volume)

    sbar_list.append(sbar)
# 模拟行情数据接收
sbar_manager = SBarManager()
cbar_manager = CBarManager(sbar_manager=sbar_manager)
swing_manager = SwingManager(cbar_manager=cbar_manager)
tred_manager = TrendManager(swing_manager=swing_manager)
# 流入模拟数据
for sbar in sbar_list:
    sbar_manager.append(sbar)

logger.debug("运行结束")
# sleep(3) # 等一会，让日志输出完
#
# region . Plotly - Cbar
#
df_cbar = cbar_manager.df_cbar.to_pandas()
df_cbar["datetime"] = pd.date_range("2025-01-01", periods=df_cbar.shape[0], freq="h")
df_cbar["open_price"] = df_cbar["high_price"]
df_cbar["close_price"] = df_cbar["low_price"]
df_cbar.insert(0, "index", range(len(df_cbar)))

# region 构建波段数据
df_swing = swing_manager.df_swing.to_pandas()
df_swing["start_datetime"] = pd.Series(dtype="datetime64[ns]")
df_swing["end_datetime"] = pd.Series(dtype="datetime64[ns]")
df_swing.insert(0, "index", range(len(df_swing)))

for i, row in enumerate(df_swing.itertuples()):
    df = df_cbar[(df_cbar["id"] >= row.start_id) & (df_cbar["id"] <= row.end_id)]
    start_datetime = df.iloc[0]["datetime"]
    end_datetime = df.iloc[-1]["datetime"]
    df_swing.at[i, "start_datetime"] = start_datetime
    df_swing.at[i, "end_datetime"] = end_datetime

xs = []
ys = []
texts = []
text_positions  = []
for i, row in enumerate(df_swing.itertuples()):
    xs += [row.start_datetime, row.end_datetime, None]
    start_index = df_cbar[(df_cbar["id"] == row.start_id)]["index"].iloc[0]
    end_index = df_cbar[(df_cbar["id"] == row.end_id)]["index"].iloc[0]
    if row.direction == Direction.UP:
        start_price = df_cbar[(df_cbar["id"] == row.start_id)]["low_price"].iloc[0]
        end_price = df_cbar[(df_cbar["id"] == row.end_id)]["high_price"].iloc[0]
        text_positions += ['bottom center', 'top center', "middle center"]
    else:
        start_price = df_cbar[(df_cbar["id"] == row.start_id)]["high_price"].iloc[0]
        end_price = df_cbar[(df_cbar["id"] == row.end_id)]["low_price"].iloc[0]
        text_positions += ['top center', 'bottom center', "middle center"]
    ys += [start_price, end_price, None]
    texts += [start_index, end_index, None]


# endregion

fig = make_subplots(
    rows=1, cols=1
)
fig.add_trace(go.Candlestick(
    x=df_cbar['datetime'],
    open=df_cbar['open_price'],
    high=df_cbar['high_price'],
    low=df_cbar['low_price'],
    close=df_cbar['close_price'],
    name='K线',
), row=1, col=1)

df_fractal_bottom = df_cbar[(df_cbar['fractal_type'] == FractalType.BOTTOM)]

fig.add_trace(go.Scatter(
    x=df_fractal_bottom['datetime'],
    y=df_fractal_bottom['low_price'] * 0.995,   # 放在K线最低价下方一点，不遮挡蜡烛
    mode='markers+text',
    name='swing point low',
    marker=dict(
        symbol='triangle-up',
        size=14,
        color='#1E90FF',
    ),
    text=df_fractal_bottom["index"],      # ← 添加序号
    textposition="bottom center",              # ← 文字位置
    textfont=dict(size=10, color="white"),
    hovertemplate=
        "<b>波段低点</b><br>" +
        "时间: %{x}<br>" +
        "价格: %{y:.2f}<br>" +
        "<extra></extra>"
), row=1, col=1)


df_fractal_top = df_cbar[(df_cbar['fractal_type'] == FractalType.TOP)]

fig.add_trace(go.Scatter(
    x=df_fractal_top['datetime'],
    y=df_fractal_top['high_price'] * 1.005,  # 放在K线最高价上方一点
    mode='markers+text',
    name='swing point high',
    marker=dict(
        symbol='triangle-down',
        size=14,
        color='#FF4500',
    ),
    text=df_fractal_top["index"],      # ← 添加序号
    textposition="top center",              # ← 文字位置
    textfont=dict(size=10, color="white"),
    hovertemplate=
        "<b>波段高点</b><br>" +
        "时间: %{x}<br>" +
        "价格: %{y:.2f}<br>" +
        "<extra></extra>"
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=xs,
    y=ys,
    name='swing segments',
    mode='lines+text',    # lines+text 支持显示文字
    line=dict(width=2, color='orange'),
    text=texts,
    textposition=text_positions,  # 文字位置
))

title = 'Swing Chart - 波段标识'
fig.update_layout(title=title,
                  height=900,
                  hovermode='x unified',  # X轴悬停联动虚线
                  )

fig.update_xaxes(
    showgrid=False,
)

fig.update_yaxes(
    showgrid=False,
)

fig.show()

# endregion

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"cbar_count": 1, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"cbar_count": 1, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"cbar_count": 2, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"fractal": "Fractal(left=CBar(id=119956736734920704, start_id=119956736722337792, end_id=119956736730726400, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 726000), fractal_type=0), middle=CBar(id=119956736743309312, start_id=119956736743309312, end_id=119956736743309312, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 728000), fractal_type=-1), right=CBar(id=119956736755892224, start_id=119956736755892224, end_id=119956736755892224, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 731000), fractal_type=0))", "event": "首次波段创建", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"start_fractal": "Fractal(left=CBar(id=119956736734920704, start_id=119956736722337792, end_id=119956736730726400, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 726000), fractal_type=0), middle=CBar(id=119956736743309312, start_id=119956736743309312, end_id=119956736743309312, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 728000), fractal_type=-1), right=CBar(id=119956736755892224, start_id=119956736755892224, end_id=119956736755892224, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 731000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=119956736864944128, start_id=119956736864944128, end_id=119956736864944128, high_price=974.1920166015625, low_price=967.3179931640625, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 757000), fractal_type=0), middle=CBar(id=119956736873332736, start_id=119956736869138432, end_id=119956736869138432, high_price=980.2589721679688, low_price=972.8519897460938, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 759000), fractal_type=1), right=CBar(id=119956736877527040, start_id=119956736877527040, end_id=119956736877527040, high_price=979.760009765625, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 760000), fractal_type=0))", "active_swing": "Swing(id=119956736877527040, direction=1, start_id=119956736743309312, end_id=119956736873332736, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 760000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=119956736877527040, direction=1, start_id=119956736743309312, end_id=119956736873332736, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 760000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=None, direction=-1, start_id=119956736873332736, end_id=119956736890109952, high_price=980.2589721679688, low_price=967.3179931640625, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=119956736885915648, direction=1, start_id=119956736743309312, end_id=119956736873332736, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 762000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"last_completed_swing": "Swing(id=119956736885915648, direction=1, start_id=119956736743309312, end_id=119956736902692864, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 762000))", "last_bar": "CBar(id=119956736902692864, start_id=119956736902692864, end_id=119956736902692864, high_price=982.2230224609375, low_price=976.85302734375, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 766000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"start_fractal": "Fractal(left=CBar(id=119956736734920704, start_id=119956736722337792, end_id=119956736730726400, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 726000), fractal_type=0), middle=CBar(id=119956736743309312, start_id=119956736743309312, end_id=119956736743309312, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 728000), fractal_type=-1), right=CBar(id=119956736755892224, start_id=119956736755892224, end_id=119956736755892224, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 731000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=119956736890109952, start_id=119956736877527040, end_id=119956736890109952, high_price=979.7579956054688, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 763000), fractal_type=-1), middle=CBar(id=119956736915275776, start_id=119956736902692864, end_id=119956736915275776, high_price=982.2230224609375, low_price=977.7880249023438, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 769000), fractal_type=1), right=CBar(id=119956736932052992, start_id=119956736932052992, end_id=119956736932052992, high_price=981.0230102539062, low_price=971.3280029296875, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 773000), fractal_type=0))", "active_swing": "Swing(id=119956736932052992, direction=1, start_id=119956736743309312, end_id=119956736915275776, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 773000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=119956736932052992, direction=1, start_id=119956736743309312, end_id=119956736915275776, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 773000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=None, direction=-1, start_id=119956736915275776, end_id=119956736944635904, high_price=982.2230224609375, low_price=971.3280029296875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=119956736940441600, direction=1, start_id=119956736743309312, end_id=119956736915275776, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 775000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"last_completed_swing": "Swing(id=119956736940441600, direction=1, start_id=119956736743309312, end_id=119956737015939072, high_price=982.3079833984375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 775000))", "last_bar": "CBar(id=119956737015939072, start_id=119956737011744768, end_id=119956737011744768, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 793000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"start_fractal": "Fractal(left=CBar(id=119956736734920704, start_id=119956736722337792, end_id=119956736730726400, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 726000), fractal_type=0), middle=CBar(id=119956736743309312, start_id=119956736743309312, end_id=119956736743309312, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 728000), fractal_type=-1), right=CBar(id=119956736755892224, start_id=119956736755892224, end_id=119956736755892224, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 731000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=119956737015939072, start_id=119956737011744768, end_id=119956737011744768, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 793000), fractal_type=0), middle=CBar(id=119956737041104896, start_id=119956737020133376, end_id=119956737036910592, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 799000), fractal_type=1), right=CBar(id=119956737045299200, start_id=119956737045299200, end_id=119956737045299200, high_price=984.6690063476562, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 800000), fractal_type=0))", "active_swing": "Swing(id=119956737045299200, direction=1, start_id=119956736743309312, end_id=119956737041104896, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 800000))", "prev_swing": null, "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=119956737045299200, direction=1, start_id=119956736743309312, end_id=119956737041104896, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 800000))", "prev_swing": null, "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=None, direction=-1, start_id=119956737041104896, end_id=119956737057882112, high_price=988.5280151367188, low_price=972.7020263671875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=119956737053687808, direction=1, start_id=119956736743309312, end_id=119956737041104896, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 802000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"start_fractal": "Fractal(left=CBar(id=119956737015939072, start_id=119956737011744768, end_id=119956737011744768, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 793000), fractal_type=0), middle=CBar(id=119956737041104896, start_id=119956737020133376, end_id=119956737036910592, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 799000), fractal_type=1), right=CBar(id=119956737057882112, start_id=119956737045299200, end_id=119956737053687808, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 803000), fractal_type=-1))", "end_fractal": "Fractal(left=CBar(id=119956737124990976, start_id=119956737124990976, end_id=119956737124990976, high_price=965.2780151367188, low_price=952.3099975585938, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 819000), fractal_type=0), middle=CBar(id=119956737150156800, start_id=119956737133379584, end_id=119956737145962496, high_price=957.35498046875, low_price=948.010009765625, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 825000), fractal_type=-1), right=CBar(id=119956737154351104, start_id=119956737154351104, end_id=119956737154351104, high_price=959.2680053710938, low_price=952.9249877929688, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 826000), fractal_type=0))", "active_swing": "Swing(id=119956737154351104, direction=-1, start_id=119956737041104896, end_id=119956737150156800, high_price=988.5280151367188, low_price=948.010009765625, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 826000))", "prev_swing": "Swing(id=119956737053687808, direction=1, start_id=119956736743309312, end_id=119956737041104896, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 802000))", "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=119956737154351104, direction=-1, start_id=119956737041104896, end_id=119956737150156800, high_price=988.5280151367188, low_price=948.010009765625, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 826000))", "prev_swing": "Swing(id=119956737053687808, direction=1, start_id=119956736743309312, end_id=119956737041104896, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 802000))", "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=None, direction=1, start_id=119956737150156800, end_id=119956737154351104, high_price=965.2780151367188, low_price=948.010009765625, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=119956737162739712, direction=-1, start_id=119956737041104896, end_id=119956737150156800, high_price=988.5280151367188, low_price=948.010009765625, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 828000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"last_completed_swing": "Swing(id=119956737162739712, direction=-1, start_id=119956737041104896, end_id=119956737183711232, high_price=988.5280151367188, low_price=943.6160278320312, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 828000))", "last_bar": "CBar(id=119956737183711232, start_id=119956737166934016, end_id=119956737179516928, high_price=955.2860107421875, low_price=943.6160278320312, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 833000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"start_fractal": "Fractal(left=CBar(id=119956737015939072, start_id=119956737011744768, end_id=119956737011744768, high_price=982.3079833984375, low_price=972.7020263671875, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 793000), fractal_type=0), middle=CBar(id=119956737041104896, start_id=119956737020133376, end_id=119956737036910592, high_price=988.5280151367188, low_price=980.6370239257812, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 799000), fractal_type=1), right=CBar(id=119956737057882112, start_id=119956737045299200, end_id=119956737053687808, high_price=983.4959716796875, low_price=974.5380249023438, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 803000), fractal_type=-1))", "end_fractal": "Fractal(left=CBar(id=119956737183711232, start_id=119956737166934016, end_id=119956737179516928, high_price=955.2860107421875, low_price=943.6160278320312, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 833000), fractal_type=0), middle=CBar(id=119956737196294144, start_id=119956737192099840, end_id=119956737192099840, high_price=945.0120239257812, low_price=937.1669921875, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 836000), fractal_type=-1), right=CBar(id=119956737221459968, start_id=119956737221459968, end_id=119956737221459968, high_price=952.7420043945312, low_price=940.0430297851562, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 842000), fractal_type=0))", "active_swing": "Swing(id=119956737217265664, direction=-1, start_id=119956737041104896, end_id=119956737196294144, high_price=988.5280151367188, low_price=937.1669921875, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 841000))", "prev_swing": "Swing(id=119956737053687808, direction=1, start_id=119956736743309312, end_id=119956737041104896, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 802000))", "event": "_valid_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=119956737217265664, direction=-1, start_id=119956737041104896, end_id=119956737196294144, high_price=988.5280151367188, low_price=937.1669921875, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 841000))", "prev_swing": "Swing(id=119956737053687808, direction=1, start_id=119956736743309312, end_id=119956737041104896, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 802000))", "event": "情况3，最后3根bar能组成分形。且完结波段。", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"active_swing": "Swing(id=None, direction=1, start_id=119956737196294144, end_id=119956737238237184, high_price=955.2860107421875, low_price=937.1669921875, is_completed=False, created_at=None)", "last_completed_swing": "Swing(id=119956737229848576, direction=-1, start_id=119956737041104896, end_id=119956737196294144, high_price=988.5280151367188, low_price=937.1669921875, is_completed=True, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 844000))", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}
{"last_completed_swing": "Swing(id=119956737229848576, direction=-1, start_id=119956737041104896, end_id=119956737292763136, high_price=988.5280151367188, low_price=933.6090087890625, is_completed=False, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 844000))", "last_bar": "CBar(id=119956737292763136, start_id=119956737292763136, end_id=119956737292763136, high_price=942.8469848632812, low_price=933.6090087890625, created_at=datetime.datetime(2025, 11, 28, 0, 25, 14, 859000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:25:14"}

In [4]:
# 测试swing 构建算法
from IPython.display import display
from pulao.logging import logger,init_logging
import logging
from time import sleep
from pulao.swing import Swing,SwingManager
from pulao.bar import CBar,CBarManager,SBarManager
from pulao.constant import EventType
init_logging(level=logging.DEBUG)
with open("./logs/pulao.log", "w"):
    pass # 每次运行前清空日志

logger.debug("开始运行")

def format_df_swing():
    # 在df_swing中显示df_cbar的索引顺序
    import polars as pl
    if "index" in cbar_manager.df_cbar.columns:
        cbar_manager.df_cbar = cbar_manager.df_cbar.drop("index")
    cbar_manager.df_cbar = cbar_manager.df_cbar.with_row_index("index")

    df_cbar = cbar_manager.df_cbar.select(["id","index"])
    df1 = swing_manager.df_swing.join(df_cbar, left_on="start_id", right_on="id", how="left")
    df2 = swing_manager.df_swing.join(df_cbar, left_on="end_id", right_on="id", how="left")
    df1 = df1.rename({"index":"start_index"})
    df2 = df2.rename({"index":"end_index"})
    df2 = df2.select(["id","end_index"])
    df1 = df1.join(df2, on="id", how="left")
    df = df1.select(["id","start_index","end_index","start_id","end_id","high_price","low_price","direction","is_completed","created_at"])

    return df


cbar_manager = CBarManager(sbar_manager=SBarManager())
swing_manager = SwingManager(cbar_manager=cbar_manager)
trend_manager = TrendManager(swing_manager=swing_manager)
df_cbar = cbar_manager.read_parquet()
cbar_manager.df_cbar = cbar_manager.df_cbar.slice(0,0)
for i in range(df_cbar.height-1):
    cbar = CBar(**df_cbar.row(i, named=True))
    cbar_manager._append_cbar(start_id=cbar.start_id, end_id=cbar.end_id, high_price=cbar.high_price, low_price=cbar.low_price,fractal_type=cbar.fractal_type)
    cbar_manager.notify(EventType.CBAR_CREATED)

logger.debug("运行结束")
sleep(0.2)


display("df_swing")
df = format_df_swing()
display(df)

display("df_cbar")
cbar_manager.df_cbar

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:28:53"}
{"event": "运行结束", "level": "debug", "logger": "__main__", "time": "2025-11-28 00:28:53"}

'df_swing'

shape: (29, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ start_ind ┆ end_index ┆ start_id  ┆ … ┆ low_price ┆ direction ┆ is_comple ┆ created_ │
│ ---       ┆ ex        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ted       ┆ at       │
│ u64       ┆ ---       ┆ u32       ┆ u64       ┆   ┆ f32       ┆ i8        ┆ ---       ┆ ---      │
│           ┆ u32       ┆           ┆           ┆   ┆           ┆           ┆ bool      ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [ms]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 119956737 ┆ 1         ┆ 24        ┆ 119956736 ┆ … ┆ 930.29797 ┆ 1         ┆ true      ┆ 2025-11- │
│ 053687808 ┆           ┆           ┆ 743309312 ┆   ┆ 4         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :14.802  │
│ 119956738 ┆ 24        ┆ 98        ┆ 119956737 ┆ … ┆ 842.13397 ┆ -1        ┆ true      ┆ 2025-11- │
│ 098069504 ┆           ┆           ┆ 041104896 ┆   ┆ 2         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :15.051  │
│ 119956738 ┆ 98        ┆ 104       ┆ 119956738 ┆ … ┆ 842.13397 ┆ 1         ┆ true      ┆ 2025-11- │
│ 186149888 ┆           ┆           ┆ 068709376 ┆   ┆ 2         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :15.072  │
│ 119956738 ┆ 104       ┆ 135       ┆ 119956738 ┆ … ┆ 834.388   ┆ -1        ┆ true      ┆ 2025-11- │
│ 697854976 ┆           ┆           ┆ 169372672 ┆   ┆           ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :15.194  │
│ 119956738 ┆ 135       ┆ 144       ┆ 119956738 ┆ … ┆ 841.73498 ┆ 1         ┆ true      ┆ 2025-11- │
│ 886598656 ┆           ┆           ┆ 672689152 ┆   ┆ 5         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :15.239  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 119956749 ┆ 635       ┆ 641       ┆ 119956749 ┆ … ┆ 752.09802 ┆ 1         ┆ true      ┆ 2025-11- │
│ 716291584 ┆           ┆           ┆ 519159296 ┆   ┆ 2         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :17.821  │
│ 119956750 ┆ 641       ┆ 653       ┆ 119956749 ┆ … ┆ 739.61102 ┆ -1        ┆ true      ┆ 2025-11- │
│ 051835904 ┆           ┆           ┆ 686931456 ┆   ┆ 3         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :17.901  │
│ 119956750 ┆ 653       ┆ 672       ┆ 119956750 ┆ … ┆ 739.61102 ┆ 1         ┆ true      ┆ 2025-11- │
│ 534180864 ┆           ┆           ┆ 022475776 ┆   ┆ 3         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :18.016  │
│ 119956751 ┆ 672       ┆ 722       ┆ 119956750 ┆ … ┆ 690.55999 ┆ -1        ┆ true      ┆ 2025-11- │
│ 876358144 ┆           ┆           ┆ 504820736 ┆   ┆ 8         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :18.336  │
│ 119956752 ┆ 722       ┆ 759       ┆ 119956751 ┆ … ┆ 690.55999 ┆ 1         ┆ false     ┆ 2025-11- │
│ 845242368 ┆           ┆           ┆ 842803712 ┆   ┆ 8         ┆           ┆           ┆ 28 00:25 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :18.567  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

'df_cbar'

shape: (760, 8)
┌───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ id         ┆ start_id   ┆ end_id     ┆ high_price ┆ low_price  ┆ fractal_ty ┆ created_at │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ pe         ┆ ---        │
│ u32   ┆ u64        ┆ u64        ┆ u64        ┆ f32        ┆ f32        ┆ ---        ┆ datetime[m │
│       ┆            ┆            ┆            ┆            ┆            ┆ i8         ┆ s]         │
╞═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ 1199567367 ┆ 1199567367 ┆ 1199567367 ┆ 942.234985 ┆ 935.924011 ┆ 0          ┆ 2025-11-28 │
│       ┆ 34920704   ┆ 22337792   ┆ 30726400   ┆            ┆            ┆            ┆ 00:25:14.7 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 26         │
│ 1     ┆ 1199567367 ┆ 1199567367 ┆ 1199567367 ┆ 939.052002 ┆ 930.297974 ┆ -1         ┆ 2025-11-28 │
│       ┆ 43309312   ┆ 43309312   ┆ 43309312   ┆            ┆            ┆            ┆ 00:25:14.7 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 28         │
│ 2     ┆ 1199567367 ┆ 1199567367 ┆ 1199567367 ┆ 951.27301  ┆ 937.492981 ┆ 0          ┆ 2025-11-28 │
│       ┆ 55892224   ┆ 55892224   ┆ 55892224   ┆            ┆            ┆            ┆ 00:25:14.7 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 31         │
│ 3     ┆ 1199567367 ┆ 1199567367 ┆ 1199567367 ┆ 955.56897  ┆ 948.888    ┆ 1          ┆ 2025-11-28 │
│       ┆ 85252352   ┆ 68475136   ┆ 81058048   ┆            ┆            ┆            ┆ 00:25:14.7 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 38         │
│ 4     ┆ 1199567367 ┆ 1199567367 ┆ 1199567367 ┆ 950.607971 ┆ 946.338989 ┆ -1         ┆ 2025-11-28 │
│       ┆ 93640960   ┆ 93640960   ┆ 93640960   ┆            ┆            ┆            ┆ 00:25:14.7 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 40         │
│ …     ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 755   ┆ 1199567527 ┆ 1199567526 ┆ 1199567526 ┆ 741.554016 ┆ 735.406982 ┆ 0          ┆ 2025-11-28 │
│       ┆ 02636032   ┆ 73275904   ┆ 90053120   ┆            ┆            ┆            ┆ 00:25:18.5 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 33         │
│ 756   ┆ 1199567527 ┆ 1199567527 ┆ 1199567527 ┆ 747.684021 ┆ 740.830994 ┆ 0          ┆ 2025-11-28 │
│       ┆ 19413248   ┆ 11024640   ┆ 11024640   ┆            ┆            ┆            ┆ 00:25:18.5 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 37         │
│ 757   ┆ 1199567527 ┆ 1199567527 ┆ 1199567527 ┆ 751.919006 ┆ 744.698975 ┆ 0          ┆ 2025-11-28 │
│       ┆ 36190464   ┆ 31996160   ┆ 31996160   ┆            ┆            ┆            ┆ 00:25:18.5 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 41         │
│ 758   ┆ 1199567528 ┆ 1199567527 ┆ 1199567528 ┆ 756.898987 ┆ 752.330994 ┆ 0          ┆ 2025-11-28 │
│       ┆ 11687936   ┆ 48773376   ┆ 07493632   ┆            ┆            ┆            ┆ 00:25:18.5 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 59         │
│ 759   ┆ 1199567528 ┆ 1199567528 ┆ 1199567528 ┆ 759.453003 ┆ 752.804993 ┆ 0          ┆ 2025-11-28 │
│       ┆ 32659456   ┆ 24270848   ┆ 24270848   ┆            ┆            ┆            ┆ 00:25:18.5 │
│       ┆            ┆            ┆            ┆            ┆            ┆            ┆ 64         │
└───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
# 可视化日志
import pandas as pd
df = pd.read_json("./logs/pulao.log",lines=True)
df = df.drop(columns=["logger","level","time"])
priority_cols = ["event"]
other_cols = [c for c in df.columns if c not in priority_cols]
df = df[priority_cols+other_cols]
df["info"] = df[other_cols].apply(lambda row: row.dropna().tolist(), axis=1)
df = df.drop(columns=other_cols)
df["info"] = df["info"].apply(lambda x: "" if x == [] else x)
df

In [ ]:
cbar_manager.read_parquet()