In [1]:
from pulao.bar.sbar import SBar
from pulao.bar.cbar_manager import CBarManager
from pulao.bar.sbar_manager import SBarManager
from pulao.swing.swing_manager import SwingManager
from pulao.trend.trend_manager import TrendManager
import logging

from pulao.keyzone.keyzone_manager import KeyZoneManager
from pulao.logging import init_logging
from pulao.mtc import MultiTimeframeContext

from pulao.constant import Timeframe

import polars as pl

from pulao.logging import logger

init_logging(level=logging.DEBUG)
open("./logs/pulao.log", "w").close()  # 每次运行前清空日志
logger.debug("开始运行")

df = pl.read_csv("../dataset/I8888.XDCE_60m.csv", try_parse_dates=True)
df = df.slice(0,100)  # test

sbar_list = []
columns = df.columns

for idx, row in enumerate(df.iter_rows()):
    row_dict = dict(zip(columns, row))
    # datetime,open,close,high,low,volume,money,open_interest,signal
    datetime = row_dict["datetime"]
    o = row_dict["open"]
    close = row_dict["close"]
    high = row_dict["high"]
    low = row_dict["low"]
    volume = row_dict["volume"]
    money = row_dict["money"]
    open_interest = row_dict["open_interest"]

    sbar = SBar(
        symbol="i8888",
        exchange="shfe",
        timeframe=Timeframe.H1,
        datetime=datetime,
        turnover=money,
        open_price=o,
        close_price=close,
        high_price=high,
        low_price=low,
        volume=volume,
    )

    sbar_list.append(sbar)
# 模拟行情数据接收
sbar_manager = SBarManager()
cbar_manager = CBarManager(sbar_manager=sbar_manager)
swing_manager = SwingManager(cbar_manager=cbar_manager)
trend_manager = TrendManager(swing_manager=swing_manager)
# 周期：manager list
mtc = MultiTimeframeContext()
mtc.register(Timeframe.M15, sbar_manager, cbar_manager, swing_manager, trend_manager)
mtc.register(Timeframe.H1, sbar_manager, cbar_manager, swing_manager, trend_manager)
mtc.register(Timeframe.D1, sbar_manager, cbar_manager, swing_manager, trend_manager)
keyzone = KeyZoneManager(mtc=mtc)

# 注入模拟数据
for sbar in sbar_list:
    sbar_manager.append(sbar)

logger.debug("运行结束")

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"cbar_count": 1, "event": "用于组成分形的cbar数量不够", "level": "info", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"swing_list": null, "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007157481472, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 22, 14, 0), volume=16884.0, turnover=1582169600.0, open_interest=0, open_price=937.425, high_price=939.407, low_price=935.924, close_price=939.407, ema_short=939.407, ema_long=939.407, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"swing_list": null, "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': 122520007161679872}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007186841600, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 22, 15, 0), volume=99312.0, turnover=9311737150.0, open_interest=0, open_price=939.488, high_price=942.235, low_price=928.389, close_price=937.413, ema_short=939.2170952380952, ema_long=939.3416229508197, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"cbar_count": 2, "event": "用于组成分形的cbar数量不够", "level": "info", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"swing_list": null, "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007245561856, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 22, 22, 0), volume=58260.0, turnover=5478055450.0, open_interest=0, open_price=934.797, high_price=939.052, low_price=930.298, close_price=938.463, ema_short=939.1452766439909, ema_long=939.3128156409567, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"fractal": "Fractal(left=CBar(id=122520007220400128, sbar_start_id=122520007157481472, sbar_end_id=122520007186841600, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 12, 5, 2, 10, 46, 33000), fractal_type=0), middle=CBar(id=122520007245565952, sbar_start_id=122520007245561856, sbar_end_id=122520007245561856, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 12, 5, 2, 10, 46, 39000), fractal_type=-1), right=CBar(id=122520007287508992, sbar_start_id=122520007283310592, sbar_end_id=122520007283310592, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 12, 5, 2, 10, 46, 49000), fractal_type=0))", "event": "首次波段创建", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"swing_list": null, "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007283310592, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 22, 23, 0), volume=97674.0, turnover=9270288750.0, open_interest=0, open_price=938.309, high_price=951.273, low_price=937.493, close_price=949.421, ema_short=940.1239169636108, ema_long=939.6442315215811, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007304298496}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007350419456, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 23, 10, 0), volume=71689.0, turnover=6857075500.0, open_interest=0, open_price=949.588, high_price=955.569, low_price=947.655, close_price=952.963, ema_short=941.3466867766002, ema_long=940.0809124552998, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"end_bar": "CBar(id=122520007287508992, sbar_start_id=122520007283310592, sbar_end_id=122520007283310592, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 12, 5, 2, 10, 46, 49000), fractal_type=0)", "event": "swing中需删除backtrack_id后，重新开始的位置", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007367213056}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': 122520007350423552}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007388168192, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 23, 11, 0), volume=32090.0, turnover=3055169950.0, open_interest=0, open_price=953.321, high_price=955.252, low_price=948.888, close_price=949.385, ema_short=942.112240416924, ema_long=940.3859645059457, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_determine_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007400767488}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007430111232, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 23, 11, 30), volume=24215.0, turnover=2299501500.0, open_interest=0, open_price=949.433, high_price=950.608, low_price=946.339, close_price=949.103, ema_short=942.7780270438836, ema_long=940.6717689483737, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007459487744}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007484637184, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 23, 14, 0), volume=19005.0, turnover=1806292750.0, open_interest=0, open_price=950.198, high_price=952.096, low_price=949.226, close_price=951.08, ema_short=943.5686911349424, ema_long=941.0130224254763, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"end_bar": "CBar(id=122520007430115328, sbar_start_id=122520007430111232, sbar_end_id=122520007430111232, high_price=950.6079711914062, low_price=946.3389892578125, created_at=datetime.datetime(2025, 12, 5, 2, 10, 46, 83000), fractal_type=-1)", "event": "swing中需删除backtrack_id后，重新开始的位置", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007501430784}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': 122520007488835584}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007526580224, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 23, 15, 0), volume=37145.0, turnover=3538036450.0, open_interest=0, open_price=951.09, high_price=953.411, low_price=948.631, close_price=949.791, ema_short=944.1612919792335, ema_long=941.3008249689033, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007543373824}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007560134656, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 23, 22, 0), volume=90937.0, turnover=8723668500.0, open_interest=0, open_price=951.758, high_price=961.795, low_price=950.804, close_price=961.218, ema_short=945.7857403621637, ema_long=941.9538471010703, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"end_bar": "CBar(id=122520007526584320, sbar_start_id=122520007484637184, sbar_end_id=122520007526580224, high_price=953.4110107421875, low_price=949.2260131835938, created_at=datetime.datetime(2025, 12, 5, 2, 10, 46, 106000), fractal_type=0)", "event": "swing中需删除backtrack_id后，重新开始的位置", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007576928256}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': 122520007564333056}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007602077696, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 23, 23, 0), volume=51179.0, turnover=4915111350.0, open_interest=0, open_price=961.231, high_price=961.342, low_price=952.804, close_price=954.138, ema_short=946.5811936610053, ema_long=942.3533275239861, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_determine_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007623065600}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007644020736, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 24, 10, 0), volume=51535.0, turnover=4905228500.0, open_interest=0, open_price=954.242, high_price=957.147, low_price=950.659, close_price=952.433, ema_short=947.1385085504334, ema_long=942.6838085887734, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007665008640}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007681769472, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 24, 11, 0), volume=31778.0, turnover=3023240750.0, open_interest=0, open_price=952.385, high_price=953.807, low_price=947.199, close_price=950.847, ema_short=947.4916982122968, ema_long=942.9514542088136, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007702757376}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007719518208, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 24, 11, 30), volume=13325.0, turnover=1268585400.0, open_interest=0, open_price=950.427, high_price=954.261, low_price=950.068, close_price=953.919, ema_short=948.103822192078, ema_long=943.3110458740985, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007748894720}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007769849856, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 24, 14, 0), volume=23842.0, turnover=2275352450.0, open_interest=0, open_price=953.262, high_price=957.67, low_price=951.556, close_price=957.108, ema_short=948.9613629356896, ema_long=943.7634050257674, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007786643456}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007803404288, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 24, 15, 0), volume=65558.0, turnover=6325667600.0, open_interest=0, open_price=956.905, high_price=963.648, low_price=956.07, close_price=963.183, ema_short=950.315804560862, ema_long=944.4001130577094, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007820197888}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007836958720, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 24, 22, 0), volume=135129.0, turnover=13092838250.0, open_interest=0, open_price=971.12, high_price=974.192, low_price=967.318, close_price=973.803, ema_short=952.5526803169704, ema_long=945.3641421377845, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, trend.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, swing.changed, {'backtrack_id': 122520007853752320}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, cbar.changed, {'backtrack_id': None}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}
{"event": "_on_mtc: 1h, bar.created, {'sbar': SBar(id=122520007883096064, symbol='i8888', exchange='shfe', timeframe=1h, datetime=datetime.datetime(2024, 1, 24, 23, 0), volume=98149.0, turnover=9562230150.0, open_interest=0, open_price=973.984, high_price=980.259, low_price=972.852, close_price=978.298, ema_short=955.004615524878, ema_long=946.4439407562178, created_at=None)}", "level": "debug", "logger": "__main__", "time": "2025-12-05 02:10:46"}

In [2]:
from typing import Optional
from pulao.constant import *

mtc.tf_mgr

{15m: {'sbar_manager': <pulao.bar.sbar_manager.SBarManager at 0x2085709dbe0>,
  'cbar_manager': <pulao.bar.cbar_manager.CBarManager at 0x2085709e3c0>,
  'swing_manager': <pulao.swing.swing_manager.SwingManager at 0x2085709e510>,
  'trend_manager': <pulao.trend.trend_manager.TrendManager at 0x2085709e660>},
 1h: {'sbar_manager': <pulao.bar.sbar_manager.SBarManager at 0x2085709dbe0>,
  'cbar_manager': <pulao.bar.cbar_manager.CBarManager at 0x2085709e3c0>,
  'swing_manager': <pulao.swing.swing_manager.SwingManager at 0x2085709e510>,
  'trend_manager': <pulao.trend.trend_manager.TrendManager at 0x2085709e660>},
 1d: {'sbar_manager': <pulao.bar.sbar_manager.SBarManager at 0x2085709dbe0>,
  'cbar_manager': <pulao.bar.cbar_manager.CBarManager at 0x2085709e3c0>,
  'swing_manager': <pulao.swing.swing_manager.SwingManager at 0x2085709e510>,
  'trend_manager': <pulao.trend.trend_manager.TrendManager at 0x2085709e660>}}

In [2]:
# 画图
import polars as pl
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pulao.constant import *

# sbar_manager = SBarManager()
# cbar_manager = CBarManager(sbar_manager=sbar_manager)
# swing_manager = SwingManager(cbar_manager=cbar_manager)
# trend_manager = TrendManager(swing_manager=cbar_manager)
# cbar_manager.read_parquet()
# swing_manager.read_parquet()
# trend_manager.read_parquet()
#
# region . Plotly - Cbar
#
df_cbar = cbar_manager.df_cbar.to_pandas()
df_cbar["datetime"] = pd.date_range("2025-01-01", periods=df_cbar.shape[0], freq="h")
df_cbar["open_price"] = df_cbar["high_price"]
df_cbar["close_price"] = df_cbar["low_price"]
if "index" in df_cbar.columns:
    del df_cbar["index"]

df_cbar.insert(0, "index", range(len(df_cbar)))

# region 构建波段数据
df_swing = swing_manager.df_swing.to_pandas()
df_swing["start_datetime"] = pd.Series(dtype="datetime64[ns]")
df_swing["end_datetime"] = pd.Series(dtype="datetime64[ns]")
if "index" in df_swing.columns:
    del df_swing["index"]
df_swing.insert(0, "index", range(len(df_swing)))

for i, row in enumerate(df_swing.itertuples()):
    df = df_cbar[
        (df_cbar["id"] >= row.cbar_start_id) & (df_cbar["id"] <= row.cbar_end_id)
    ]
    start_datetime = df.iloc[0]["datetime"]
    end_datetime = df.iloc[-1]["datetime"]
    df_swing.at[i, "start_datetime"] = start_datetime
    df_swing.at[i, "end_datetime"] = end_datetime

xs_swing = []
ys_swing = []
texts_swing = []
text_positions_swing = []
for i, row in enumerate(df_swing.itertuples()):
    xs_swing += [row.start_datetime, row.end_datetime, None]
    print("df_swing - "+str(i),row)
    start_index = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["index"].iloc[0]
    end_index = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["index"].iloc[0]
    if row.direction == Direction.UP:
        start_price = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["low_price"].iloc[0]
        end_price = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["high_price"].iloc[0]
        text_positions_swing += ["bottom center", "top center", "middle center"]
    else:
        start_price = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["high_price"].iloc[
            0
        ]
        end_price = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["low_price"].iloc[0]
        text_positions_swing += ["top center", "bottom center", "middle center"]
    ys_swing += [start_price, end_price, None]
    texts_swing += [start_index, end_index, None]
# endregion

# region 构建趋势数据
df_trend = trend_manager.df_trend.to_pandas()
df_trend["start_datetime"] = pd.Series(dtype="datetime64[ns]")
df_trend["end_datetime"] = pd.Series(dtype="datetime64[ns]")
df_trend.insert(0, "index", range(len(df_trend)))

for i, row in enumerate(df_trend.itertuples()):
    print("df_trend[datatime] - "+ str(i), row)
    df = df_swing[
        (df_swing["id"] >= row.swing_start_id) & (df_swing["id"] <= row.swing_end_id)
    ]
    start_datetime = df.iloc[0]["start_datetime"]
    end_datetime = df.iloc[-1]["end_datetime"]
    df_trend.at[i, "start_datetime"] = start_datetime
    df_trend.at[i, "end_datetime"] = end_datetime

xs_trend = []
ys_trend = []
texts_trend = []
text_positions_trend = []
for i, row in enumerate(df_trend.itertuples()):
    xs_trend += [row.start_datetime, row.end_datetime, None]
    print("df_trend[marker] - "+ str(i), row)
    start_index = df_swing[(df_swing["id"] == row.swing_start_id)]["index"].iloc[0]
    end_index = df_swing[(df_swing["id"] == row.swing_end_id)]["index"].iloc[0]
    if row.direction == Direction.UP:
        start_price = df_swing[(df_swing["id"] == row.swing_start_id)]["low_price"].iloc[0]
        end_price = df_swing[(df_swing["id"] == row.swing_end_id)]["high_price"].iloc[0]
        text_positions_trend += ["bottom center", "top center", "middle center"]
    else:
        start_price = df_swing[(df_swing["id"] == row.swing_start_id)]["high_price"].iloc[
            0
        ]
        end_price = df_swing[(df_swing["id"] == row.swing_end_id)]["low_price"].iloc[0]
        text_positions_trend += ["top center", "bottom center", "middle center"]
    ys_trend += [start_price, end_price, None]
    texts_trend += [start_index, end_index, None]
#endregion

# region fig
fig = make_subplots(rows=1, cols=1)
fig.add_trace(
    go.Candlestick(
        x=df_cbar["datetime"],
        open=df_cbar["open_price"],
        high=df_cbar["high_price"],
        low=df_cbar["low_price"],
        close=df_cbar["close_price"],
        name="K线",
    ),
    row=1,
    col=1,
)
#
# df_fractal_bottom = df_cbar[(df_cbar["fractal_type"] == FractalType.BOTTOM)]
#
# fig.add_trace(
#     go.Scatter(
#         x=df_fractal_bottom["datetime"],
#         y=df_fractal_bottom["low_price"] * 0.995,  # 放在K线最低价下方一点，不遮挡蜡烛
#         mode="markers+text",
#         name="swing point low",
#         marker=dict(
#             symbol="triangle-up",
#             size=14,
#             color="#1E90FF",
#         ),
#         text=df_fractal_bottom["index"],  # ← 添加序号
#         textposition="bottom center",  # ← 文字位置
#         textfont=dict(size=10, color="white"),
#         hovertemplate="<b>波段低点</b><br>"
#         + "时间: %{x}<br>"
#         + "价格: %{y:.2f}<br>"
#         + "<extra></extra>",
#     ),
#     row=1,
#     col=1,
# )
#
#
# df_fractal_top = df_cbar[(df_cbar["fractal_type"] == FractalType.TOP)]
#
# fig.add_trace(
#     go.Scatter(
#         x=df_fractal_top["datetime"],
#         y=df_fractal_top["high_price"] * 1.005,  # 放在K线最高价上方一点
#         mode="markers+text",
#         name="swing point high",
#         marker=dict(
#             symbol="triangle-down",
#             size=14,
#             color="#FF4500",
#         ),
#         text=df_fractal_top["index"],  # ← 添加序号
#         textposition="top center",  # ← 文字位置
#         textfont=dict(size=10, color="white"),
#         hovertemplate="<b>波段高点</b><br>"
#         + "时间: %{x}<br>"
#         + "价格: %{y:.2f}<br>"
#         + "<extra></extra>",
#     ),
#     row=1,
#     col=1,
# )

fig.add_trace(
    go.Scatter(
        x=xs_swing,
        y=ys_swing,
        name="swing segments",
        mode="lines",  # lines+text 支持显示文字
        line=dict(width=2, color="orange"),
        text=texts_swing,
        textposition=text_positions_swing,  # 文字位置
    )
)

fig.add_trace(
    go.Scatter(
        x=xs_trend,
        y=ys_trend,
        name="trend segments",
        mode="lines",  # lines+text 支持显示文字
        line=dict(width=2, color="red"),
        text=texts_trend,
        textposition=text_positions_trend,  # 文字位置
    )
)

title = "Swing Chart"
fig.update_layout(
    title=title,
    height=900,
    hovermode="x unified",  # X轴悬停联动虚线
)

fig.update_xaxes(
    showgrid=False,
)

fig.update_yaxes(
    showgrid=False,
)

fig.show()
# endregion

# endregion

df_swing - 0 Pandas(Index=0, index=0, id=122485266626658304, cbar_start_id=122485265880059904, cbar_end_id=122485266597285888, sbar_start_id=122485265875861504, sbar_end_id=122485266555338752, high_price=988.5280151367188, low_price=930.2979736328125, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:43.230000'), start_datetime=Timestamp('2025-01-01 01:00:00'), end_datetime=Timestamp('2025-01-02 00:00:00'))
df_swing - 1 Pandas(Index=1, index=1, id=122485267859783680, cbar_start_id=122485266597285888, cbar_end_id=122485267813634048, sbar_start_id=122485266555338752, sbar_end_id=122485267788464128, high_price=988.5280151367188, low_price=906.1430053710938, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:43.524000'), start_datetime=Timestamp('2025-01-02 00:00:00'), end_datetime=Timestamp('2025-01-03 04:00:00'))
df_swing - 2 Pandas(Index=2, index=2, id=122485268283408384, cbar_start_id=122485267813634048, cbar_end_id=122485268245647360, sbar_start_id=122485267788464128, sbar_end_id=122485268245643264, high_price=955.9249877929688, low_price=906.1430053710938, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:43.625000'), start_datetime=Timestamp('2025-01-03 04:00:00'), end_datetime=Timestamp('2025-01-03 19:00:00'))
df_swing - 3 Pandas(Index=3, index=3, id=122485269260681216, cbar_start_id=122485268245647360, cbar_end_id=122485269231308800, sbar_start_id=122485268245643264, sbar_end_id=122485269227110400, high_price=955.9249877929688, low_price=842.1339721679688, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:43.858000'), start_datetime=Timestamp('2025-01-03 19:00:00'), end_datetime=Timestamp('2025-01-05 02:00:00'))
df_swing - 4 Pandas(Index=4, index=4, id=122485269403287552, cbar_start_id=122485269231308800, cbar_end_id=122485269369720832, sbar_start_id=122485269227110400, sbar_end_id=122485269365522432, high_price=879.8569946289062, low_price=842.1339721679688, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:43.892000'), start_datetime=Timestamp('2025-01-05 02:00:00'), end_datetime=Timestamp('2025-01-05 08:00:00'))
df_swing - 5 Pandas(Index=5, index=5, id=122485270309257216, cbar_start_id=122485269369720832, cbar_end_id=122485270015643648, sbar_start_id=122485269365522432, sbar_end_id=122485270015639552, high_price=879.8569946289062, low_price=834.3880004882812, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:44.108000'), start_datetime=Timestamp('2025-01-05 08:00:00'), end_datetime=Timestamp('2025-01-06 07:00:00'))
df_swing - 6 Pandas(Index=6, index=6, id=122485270640607232, cbar_start_id=122485270015643648, cbar_end_id=122485270602846208, sbar_start_id=122485270015639552, sbar_end_id=122485270569287680, high_price=873.1190185546875, low_price=834.3880004882812, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:44.187000'), start_datetime=Timestamp('2025-01-06 07:00:00'), end_datetime=Timestamp('2025-01-07 00:00:00'))
df_swing - 7 Pandas(Index=7, index=7, id=122485271840178176, cbar_start_id=122485270602846208, cbar_end_id=122485271794028544, sbar_start_id=122485270569287680, sbar_end_id=122485271789830144, high_price=873.1190185546875, low_price=748.4650268554688, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:44.473000'), start_datetime=Timestamp('2025-01-07 00:00:00'), end_datetime=Timestamp('2025-01-08 10:00:00'))
df_swing - 8 Pandas(Index=8, index=8, id=122485272767119360, cbar_start_id=122485271794028544, cbar_end_id=122485272729358336, sbar_start_id=122485271789830144, sbar_end_id=122485272695799808, high_price=829.7630004882812, low_price=748.4650268554688, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:44.695000'), start_datetime=Timestamp('2025-01-08 10:00:00'), end_datetime=Timestamp('2025-01-09 12:00:00'))
df_swing - 9 Pandas(Index=9, index=9, id=122485273790529536, cbar_start_id=122485272729358336, cbar_end_id=122485273748574208, sbar_start_id=122485272695799808, sbar_end_id=122485273694044160, high_price=829.7630004882812, low_price=731.4290161132812, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:44.938000'), start_datetime=Timestamp('2025-01-09 12:00:00'), end_datetime=Timestamp('2025-01-10 13:00:00'))
df_swing - 10 Pandas(Index=10, index=10, id=122485276919480320, cbar_start_id=122485273748574208, cbar_end_id=122485276864942080, sbar_start_id=122485273694044160, sbar_end_id=122485276860743680, high_price=891.5170288085938, low_price=731.4290161132812, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:45.684000'), start_datetime=Timestamp('2025-01-10 13:00:00'), end_datetime=Timestamp('2025-01-14 02:00:00'))
df_swing - 11 Pandas(Index=11, index=11, id=122485277598957568, cbar_start_id=122485276864942080, cbar_end_id=122485277540225024, sbar_start_id=122485276860743680, sbar_end_id=122485277536026624, high_price=891.5170288085938, low_price=857.7769775390625, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:45.846000'), start_datetime=Timestamp('2025-01-14 02:00:00'), end_datetime=Timestamp('2025-01-14 19:00:00'))
df_swing - 12 Pandas(Index=12, index=12, id=122485277787701248, cbar_start_id=122485277540225024, cbar_end_id=122485277745745920, sbar_start_id=122485277536026624, sbar_end_id=122485277745741824, high_price=897.0020141601562, low_price=857.7769775390625, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:45.891000'), start_datetime=Timestamp('2025-01-14 19:00:00'), end_datetime=Timestamp('2025-01-15 01:00:00'))
df_swing - 13 Pandas(Index=13, index=13, id=122485278660116480, cbar_start_id=122485277745745920, cbar_end_id=122485278613966848, sbar_start_id=122485277745741824, sbar_end_id=122485278609768448, high_price=897.0020141601562, low_price=852.1500244140625, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:46.099000'), start_datetime=Timestamp('2025-01-15 01:00:00'), end_datetime=Timestamp('2025-01-16 02:00:00'))
df_swing - 14 Pandas(Index=14, index=14, id=122485278827888640, cbar_start_id=122485278613966848, cbar_end_id=122485278777544704, sbar_start_id=122485278609768448, sbar_end_id=122485278735597568, high_price=886.3670043945312, low_price=852.1500244140625, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:46.139000'), start_datetime=Timestamp('2025-01-16 02:00:00'), end_datetime=Timestamp('2025-01-16 06:00:00'))
df_swing - 15 Pandas(Index=15, index=15, id=122485279205376000, cbar_start_id=122485278777544704, cbar_end_id=122485279159226368, sbar_start_id=122485278735597568, sbar_end_id=122485279155027968, high_price=886.3670043945312, low_price=847.4390258789062, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:46.229000'), start_datetime=Timestamp('2025-01-16 06:00:00'), end_datetime=Timestamp('2025-01-16 15:00:00'))
df_swing - 16 Pandas(Index=16, index=16, id=122485280438501376, cbar_start_id=122485279159226368, cbar_end_id=122485280367185920, sbar_start_id=122485279155027968, sbar_end_id=122485280362987520, high_price=923.666015625, low_price=847.4390258789062, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:46.523000'), start_datetime=Timestamp('2025-01-16 15:00:00'), end_datetime=Timestamp('2025-01-17 19:00:00'))
df_swing - 17 Pandas(Index=17, index=17, id=122485281084424192, cbar_start_id=122485280367185920, cbar_end_id=122485281038274560, sbar_start_id=122485280362987520, sbar_end_id=122485281034076160, high_price=923.666015625, low_price=889.3870239257812, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:46.677000'), start_datetime=Timestamp('2025-01-17 19:00:00'), end_datetime=Timestamp('2025-01-18 11:00:00'))
df_swing - 18 Pandas(Index=18, index=18, id=122485281256390656, cbar_start_id=122485281038274560, cbar_end_id=122485281206046720, sbar_start_id=122485281034076160, sbar_end_id=122485281168293888, high_price=910.8989868164062, low_price=889.3870239257812, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:46.718000'), start_datetime=Timestamp('2025-01-18 11:00:00'), end_datetime=Timestamp('2025-01-18 15:00:00'))
df_swing - 19 Pandas(Index=19, index=19, id=122485282871197696, cbar_start_id=122485281206046720, cbar_end_id=122485282825048064, sbar_start_id=122485281168293888, sbar_end_id=122485282816655360, high_price=910.8989868164062, low_price=820.2650146484375, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:47.103000'), start_datetime=Timestamp('2025-01-18 15:00:00'), end_datetime=Timestamp('2025-01-19 21:00:00'))
df_swing - 20 Pandas(Index=20, index=20, id=122485283215130624, cbar_start_id=122485282825048064, cbar_end_id=122485283164786688, sbar_start_id=122485282816655360, sbar_end_id=122485283156393984, high_price=846.0089721679688, low_price=820.2650146484375, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:47.185000'), start_datetime=Timestamp('2025-01-19 21:00:00'), end_datetime=Timestamp('2025-01-20 05:00:00'))
df_swing - 21 Pandas(Index=21, index=21, id=122485283882024960, cbar_start_id=122485283164786688, cbar_end_id=122485283835875328, sbar_start_id=122485283156393984, sbar_end_id=122485283831676928, high_price=846.0089721679688, low_price=793.2050170898438, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:47.344000'), start_datetime=Timestamp('2025-01-20 05:00:00'), end_datetime=Timestamp('2025-01-20 20:00:00'))
df_swing - 22 Pandas(Index=22, index=22, id=122485284213374976, cbar_start_id=122485283835875328, cbar_end_id=122485284154642432, sbar_start_id=122485283831676928, sbar_end_id=122485284146249728, high_price=831.197998046875, low_price=793.2050170898438, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:47.423000'), start_datetime=Timestamp('2025-01-20 20:00:00'), end_datetime=Timestamp('2025-01-21 02:00:00'))
df_swing - 23 Pandas(Index=23, index=23, id=122485284418895872, cbar_start_id=122485284154642432, cbar_end_id=122485284368551936, sbar_start_id=122485284146249728, sbar_end_id=122485284364353536, high_price=831.197998046875, low_price=802.4829711914062, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:47.472000'), start_datetime=Timestamp('2025-01-21 02:00:00'), end_datetime=Timestamp('2025-01-21 07:00:00'))
df_swing - 24 Pandas(Index=24, index=24, id=122485284716691456, cbar_start_id=122485284368551936, cbar_end_id=122485284662153216, sbar_start_id=122485284364353536, sbar_end_id=122485284653760512, high_price=832.1710205078125, low_price=802.4829711914062, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:47.543000'), start_datetime=Timestamp('2025-01-21 07:00:00'), end_datetime=Timestamp('2025-01-21 14:00:00'))
df_swing - 25 Pandas(Index=25, index=25, id=122485285828182016, cbar_start_id=122485284662153216, cbar_end_id=122485285773643776, sbar_start_id=122485284653760512, sbar_end_id=122485285765251072, high_price=832.1710205078125, low_price=784.0599975585938, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:47.808000'), start_datetime=Timestamp('2025-01-21 14:00:00'), end_datetime=Timestamp('2025-01-22 15:00:00'))
df_swing - 26 Pandas(Index=26, index=26, id=122485287673675776, cbar_start_id=122485285773643776, cbar_end_id=122485287623331840, sbar_start_id=122485285765251072, sbar_end_id=122485287572996096, high_price=863.708984375, low_price=784.0599975585938, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:48.248000'), start_datetime=Timestamp('2025-01-22 15:00:00'), end_datetime=Timestamp('2025-01-24 07:00:00'))
df_swing - 27 Pandas(Index=27, index=27, id=122485288592228352, cbar_start_id=122485287623331840, cbar_end_id=122485288546078720, sbar_start_id=122485287572996096, sbar_end_id=122485288537686016, high_price=863.708984375, low_price=802.969970703125, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:48.467000'), start_datetime=Timestamp('2025-01-24 07:00:00'), end_datetime=Timestamp('2025-01-25 03:00:00'))
df_swing - 28 Pandas(Index=28, index=28, id=122485289183625216, cbar_start_id=122485288546078720, cbar_end_id=122485289133281280, sbar_start_id=122485288537686016, sbar_end_id=122485289129082880, high_price=834.1589965820312, low_price=802.969970703125, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:48.608000'), start_datetime=Timestamp('2025-01-25 03:00:00'), end_datetime=Timestamp('2025-01-25 15:00:00'))
df_swing - 29 Pandas(Index=29, index=29, id=122485291222056960, cbar_start_id=122485289133281280, cbar_end_id=122485291175907328, sbar_start_id=122485289129082880, sbar_end_id=122485291171708928, high_price=834.1589965820312, low_price=752.0980224609375, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:49.094000'), start_datetime=Timestamp('2025-01-25 15:00:00'), end_datetime=Timestamp('2025-01-27 11:00:00'))
df_swing - 30 Pandas(Index=30, index=30, id=122485291565989888, cbar_start_id=122485291175907328, cbar_end_id=122485291490480128, sbar_start_id=122485291171708928, sbar_end_id=122485291423367168, high_price=782.0349731445312, low_price=752.0980224609375, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:49.176000'), start_datetime=Timestamp('2025-01-27 11:00:00'), end_datetime=Timestamp('2025-01-27 17:00:00'))
df_swing - 31 Pandas(Index=31, index=31, id=122485292241272832, cbar_start_id=122485291490480128, cbar_end_id=122485292182540288, sbar_start_id=122485291423367168, sbar_end_id=122485292174147584, high_price=782.0349731445312, low_price=739.6110229492188, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:49.337000'), start_datetime=Timestamp('2025-01-27 17:00:00'), end_datetime=Timestamp('2025-01-28 05:00:00'))
df_swing - 32 Pandas(Index=32, index=32, id=122485293289848832, cbar_start_id=122485292182540288, cbar_end_id=122485293222727680, sbar_start_id=122485292174147584, sbar_end_id=122485293159809024, high_price=793.218017578125, low_price=739.6110229492188, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:49.587000'), start_datetime=Timestamp('2025-01-28 05:00:00'), end_datetime=Timestamp('2025-01-29 00:00:00'))
df_swing - 33 Pandas(Index=33, index=33, id=122485295772876800, cbar_start_id=122485293222727680, cbar_end_id=122485295718338560, sbar_start_id=122485293159809024, sbar_end_id=122485295709945856, high_price=793.218017578125, low_price=690.5599975585938, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:50.179000'), start_datetime=Timestamp('2025-01-29 00:00:00'), end_datetime=Timestamp('2025-01-31 02:00:00'))
df_swing - 34 Pandas(Index=34, index=34, id=122485298507563008, cbar_start_id=122485295718338560, cbar_end_id=122485298444636160, sbar_start_id=122485295709945856, sbar_end_id=122485298436243456, high_price=767.0960083007812, low_price=690.5599975585938, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:50.831000'), start_datetime=Timestamp('2025-01-31 02:00:00'), end_datetime=Timestamp('2025-02-02 08:00:00'))
df_swing - 35 Pandas(Index=35, index=35, id=122485300151730176, cbar_start_id=122485298444636160, cbar_end_id=122485300088803328, sbar_start_id=122485298436243456, sbar_end_id=122485300080410624, high_price=767.0960083007812, low_price=662.2420043945312, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:51.223000'), start_datetime=Timestamp('2025-02-02 08:00:00'), end_datetime=Timestamp('2025-02-03 12:00:00'))
df_swing - 36 Pandas(Index=36, index=36, id=122485301347106816, cbar_start_id=122485300088803328, cbar_end_id=122485301284179968, sbar_start_id=122485300080410624, sbar_end_id=122485301225455616, high_price=712.0469970703125, low_price=662.2420043945312, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:51.508000'), start_datetime=Timestamp('2025-02-03 12:00:00'), end_datetime=Timestamp('2025-02-04 14:00:00'))
df_swing - 37 Pandas(Index=37, index=37, id=122485301636513792, cbar_start_id=122485301284179968, cbar_end_id=122485301569392640, sbar_start_id=122485301225455616, sbar_end_id=122485301560999936, high_price=712.0469970703125, low_price=669.4769897460938, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:51.577000'), start_datetime=Timestamp('2025-02-04 14:00:00'), end_datetime=Timestamp('2025-02-04 20:00:00'))
df_swing - 38 Pandas(Index=38, index=38, id=122485302072721408, cbar_start_id=122485301569392640, cbar_end_id=122485302005600256, sbar_start_id=122485301560999936, sbar_end_id=122485301993013248, high_price=702.2169799804688, low_price=669.4769897460938, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:51.681000'), start_datetime=Timestamp('2025-02-04 20:00:00'), end_datetime=Timestamp('2025-02-05 02:00:00'))
df_swing - 39 Pandas(Index=39, index=39, id=122485302550872064, cbar_start_id=122485302005600256, cbar_end_id=122485302487945216, sbar_start_id=122485301993013248, sbar_end_id=122485302479552512, high_price=702.2169799804688, low_price=657.4080200195312, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:51.795000'), start_datetime=Timestamp('2025-02-05 02:00:00'), end_datetime=Timestamp('2025-02-05 10:00:00'))
df_swing - 40 Pandas(Index=40, index=40, id=122485304027267072, cbar_start_id=122485302487945216, cbar_end_id=122485303955951616, sbar_start_id=122485302479552512, sbar_end_id=122485303947558912, high_price=842.4299926757812, low_price=657.4080200195312, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:52.147000'), start_datetime=Timestamp('2025-02-05 10:00:00'), end_datetime=Timestamp('2025-02-06 12:00:00'))
df_swing - 41 Pandas(Index=41, index=41, id=122485307982495744, cbar_start_id=122485303955951616, cbar_end_id=122485307776962560, sbar_start_id=122485303947558912, sbar_end_id=122485307768569856, high_price=842.4299926757812, low_price=737.958984375, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:53.090000'), start_datetime=Timestamp('2025-02-06 12:00:00'), end_datetime=Timestamp('2025-02-08 20:00:00'))
df_swing - 42 Pandas(Index=42, index=42, id=122485311073697792, cbar_start_id=122485307776962560, cbar_end_id=122485310989799424, sbar_start_id=122485307768569856, sbar_end_id=122485310981406720, high_price=798.0850219726562, low_price=737.958984375, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:53.827000'), start_datetime=Timestamp('2025-02-08 20:00:00'), end_datetime=Timestamp('2025-02-11 04:00:00'))
df_swing - 43 Pandas(Index=43, index=43, id=122485312973717504, cbar_start_id=122485310989799424, cbar_end_id=122485312889819136, sbar_start_id=122485310981406720, sbar_end_id=122485312881426432, high_price=798.0850219726562, low_price=732.27099609375, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:54.280000'), start_datetime=Timestamp('2025-02-11 04:00:00'), end_datetime=Timestamp('2025-02-12 10:00:00'))
df_swing - 44 Pandas(Index=44, index=44, id=122485317226741760, cbar_start_id=122485312889819136, cbar_end_id=122485317168009216, sbar_start_id=122485312881426432, sbar_end_id=122485317155422208, high_price=807.2020263671875, low_price=732.27099609375, direction=1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:55.294000'), start_datetime=Timestamp('2025-02-12 10:00:00'), end_datetime=Timestamp('2025-02-15 10:00:00'))
df_swing - 45 Pandas(Index=45, index=45, id=122485317902024704, cbar_start_id=122485317168009216, cbar_end_id=122485317834903552, sbar_start_id=122485317155422208, sbar_end_id=122485317763596288, high_price=807.2020263671875, low_price=776.8159790039062, direction=-1, is_completed=True, created_at=Timestamp('2025-12-04 23:52:55.455000'), start_datetime=Timestamp('2025-02-15 10:00:00'), end_datetime=Timestamp('2025-02-15 22:00:00'))

In [7]:
trend_manager.df_trend
format_df_trend()

NameError: name 'format_df_trend' is not defined

In [9]:
from typing import List

# 测试构建算法
from IPython.display import display
from pulao.logging import logger, init_logging
import logging
from time import sleep
from pulao.swing import Swing, SwingManager
from pulao.trend import Trend, TrendManager
from pulao.bar import CBar, CBarManager, SBarManager
from pulao.constant import *
import polars as pl

init_logging(level=logging.DEBUG)
with open("./logs/pulao.log", "w"):
    pass  # 每次运行前清空日志

logger.debug("开始运行")


def format_df_trend():
    import polars as pl

    if "index" in swing_manager.df_swing.columns:
        swing_manager.df_swing = swing_manager.df_swing.drop("index")
    swing_manager.df_swing = swing_manager.df_swing.with_row_index("index")

    df_swing_tmp = swing_manager.df_swing.select(["id", "index"])
    df1 = trend_manager.df_trend.join(
        df_swing_tmp, left_on="swing_start_id", right_on="id", how="left"
    )
    df2 = trend_manager.df_trend.join(
        df_swing_tmp, left_on="swing_end_id", right_on="id", how="left"
    )
    df1 = df1.rename({"index": "swing_start_index"})
    df2 = df2.rename({"index": "swing_end_index"})
    df2 = df2.select(["id", "swing_end_index"])
    df1 = df1.join(df2, on="id", how="left")
    df = df1.select(
        [
            "id",
            "swing_start_index",
            "swing_end_index",
            "swing_start_id",
            "swing_end_id",
            "high_price",
            "low_price",
            "direction",
            "is_completed",
            "created_at",
        ]
    )

    return df


cbar_manager = CBarManager(sbar_manager=SBarManager())
swing_manager = SwingManager(cbar_manager=cbar_manager)
trend_manager = TrendManager(swing_manager=swing_manager)
df_cbar = cbar_manager.read_parquet()
df_swing = swing_manager.read_parquet()
df_swing = trend_manager.read_parquet()
# df_swing = df_swing.slice(18,20)
# swing_manager.df_swing = swing_manager.df_swing.slice(0, 0)  # 清空原数据
# trend_manager.df_trend = trend_manager.df_trend.slice(0, 0)
# for i in range(df_swing.height - 1):
#     swing = Swing(**df_swing.row(i, named=True))
#     new_swing = {
#             "id": swing.id,
#             "direction": swing.direction.value,
#             "cbar_start_id": swing.cbar_start_id,
#             "cbar_end_id": swing.cbar_end_id,
#             "sbar_start_id": swing.sbar_start_id,
#             "sbar_end_id": swing.sbar_end_id,
#             "high_price": swing.high_price,
#             "low_price": swing.low_price,
#             "is_completed": swing.is_completed,
#             "created_at": swing.created_at,
#         }
#
#     swing_manager.df_swing = swing_manager.df_swing.vstack(
#         pl.DataFrame([new_swing], schema=swing_manager.df_swing.schema)
#     )
#     swing_manager.notify(EventType.SWING_CHANGED, payload=dict(backtrack_id=None))


logger.debug("运行结束")
sleep(0.2)


display("df_trend")
df = format_df_trend()
display(df)

display("df_swing")
swing_manager.df_swing

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-12-03 16:34:42"}
{"event": "运行结束", "level": "debug", "logger": "__main__", "time": "2025-12-03 16:34:42"}

'df_trend'

shape: (7, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ swing_sta ┆ swing_end ┆ swing_sta ┆ … ┆ low_price ┆ direction ┆ is_comple ┆ created_ │
│ ---       ┆ rt_index  ┆ _index    ┆ rt_id     ┆   ┆ ---       ┆ ---       ┆ ted       ┆ at       │
│ u64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f32       ┆ i8        ┆ ---       ┆ ---      │
│           ┆ u32       ┆ u32       ┆ u64       ┆   ┆           ┆           ┆ bool      ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [ms]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 122008733 ┆ 1         ┆ 9         ┆ 122008716 ┆ … ┆ 731.42901 ┆ -1        ┆ true      ┆ 2025-12- │
│ 705314304 ┆           ┆           ┆ 089233408 ┆   ┆ 6         ┆           ┆           ┆ 03 16:19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :08.928  │
│ 122008734 ┆ 10        ┆ 16        ┆ 122008727 ┆ … ┆ 731.42901 ┆ 1         ┆ true      ┆ 2025-12- │
│ 015692800 ┆           ┆           ┆ 548071936 ┆   ┆ 6         ┆           ┆           ┆ 03 16:19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :09.002  │
│ 122008759 ┆ 17        ┆ 39        ┆ 122008733 ┆ … ┆ 657.40802 ┆ -1        ┆ true      ┆ 2025-12- │
│ 303151616 ┆           ┆           ┆ 055193088 ┆   ┆           ┆           ┆           ┆ 03 16:19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :15.031  │
│ 122008779 ┆ 40        ┆ 40        ┆ 122008760 ┆ … ┆ 657.40802 ┆ 1         ┆ true      ┆ 2025-12- │
│ 339341824 ┆           ┆           ┆ 431415296 ┆   ┆           ┆           ┆           ┆ 03 16:19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :19.808  │
│ 122008783 ┆ 41        ┆ 43        ┆ 122008767 ┆ … ┆ 732.27099 ┆ -1        ┆ true      ┆ 2025-12- │
│ 177129984 ┆           ┆           ┆ 540760576 ┆   ┆ 6         ┆           ┆           ┆ 03 16:19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :20.723  │
│ 122008801 ┆ 44        ┆ 56        ┆ 122008778 ┆ … ┆ 732.27099 ┆ 1         ┆ true      ┆ 2025-12- │
│ 527209984 ┆           ┆           ┆ 232041472 ┆   ┆ 6         ┆           ┆           ┆ 03 16:19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :25.098  │
│ 122008801 ┆ 56        ┆ 56        ┆ 122008801 ┆ … ┆ 741.73199 ┆ -1        ┆ false     ┆ 2025-12- │
│ 728536576 ┆           ┆           ┆ 187467264 ┆   ┆ 5         ┆           ┆           ┆ 03 16:19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :25.146  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

'df_swing'

shape: (58, 11)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ index ┆ id         ┆ cbar_start ┆ cbar_end_i ┆ … ┆ low_price ┆ direction ┆ is_comple ┆ created_a │
│ ---   ┆ ---        ┆ _id        ┆ d          ┆   ┆ ---       ┆ ---       ┆ ted       ┆ t         │
│ u32   ┆ u64        ┆ ---        ┆ ---        ┆   ┆ f32       ┆ i8        ┆ ---       ┆ ---       │
│       ┆            ┆ u64        ┆ u64        ┆   ┆           ┆           ┆ bool      ┆ datetime[ │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ ms]       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0     ┆ 1220087137 ┆ 1220087125 ┆ 1220087136 ┆ … ┆ 930.29797 ┆ 1         ┆ true      ┆ 2025-12-0 │
│       ┆ 40423168   ┆ 11488000   ┆ 94281728   ┆   ┆ 4         ┆           ┆           ┆ 3 16:19:0 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 4.168     │
│ 1     ┆ 1220087160 ┆ 1220087136 ┆ 1220087160 ┆ … ┆ 906.14300 ┆ -1        ┆ true      ┆ 2025-12-0 │
│       ┆ 89233408   ┆ 94281728   ┆ 26314752   ┆   ┆ 5         ┆           ┆           ┆ 3 16:19:0 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 4.728     │
│ 2     ┆ 1220087166 ┆ 1220087160 ┆ 1220087166 ┆ … ┆ 906.14300 ┆ 1         ┆ true      ┆ 2025-12-0 │
│       ┆ 89018880   ┆ 26314752   ┆ 59654656   ┆   ┆ 5         ┆           ┆           ┆ 3 16:19:0 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 4.871     │
│ 3     ┆ 1220087181 ┆ 1220087166 ┆ 1220087180 ┆ … ┆ 842.13397 ┆ -1        ┆ true      ┆ 2025-12-0 │
│       ┆ 27665152   ┆ 59654656   ┆ 89912320   ┆   ┆ 2         ┆           ┆           ┆ 3 16:19:0 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 5.214     │
│ 4     ┆ 1220087183 ┆ 1220087180 ┆ 1220087182 ┆ … ┆ 842.13397 ┆ 1         ┆ true      ┆ 2025-12-0 │
│       ┆ 16408832   ┆ 89912320   ┆ 61878784   ┆   ┆ 2         ┆           ┆           ┆ 3 16:19:0 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 5.259     │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 53    ┆ 1220087900 ┆ 1220087878 ┆ 1220087899 ┆ … ┆ 741.73199 ┆ -1        ┆ true      ┆ 2025-12-0 │
│       ┆ 30618624   ┆ 16022016   ┆ 38339840   ┆   ┆ 5         ┆           ┆           ┆ 3 16:19:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 2.357     │
│ 54    ┆ 1220087975 ┆ 1220087899 ┆ 1220087974 ┆ … ┆ 741.73199 ┆ 1         ┆ true      ┆ 2025-12-0 │
│       ┆ 80365824   ┆ 38339840   ┆ 79698432   ┆   ┆ 5         ┆           ┆           ┆ 3 16:19:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 4.157     │
│ 55    ┆ 1220087994 ┆ 1220087974 ┆ 1220087992 ┆ … ┆ 782.69799 ┆ -1        ┆ true      ┆ 2025-12-0 │
│       ┆ 42636800   ┆ 79698432   ┆ 32917504   ┆   ┆ 8         ┆           ┆           ┆ 3 16:19:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 4.601     │
│ 56    ┆ 1220088011 ┆ 1220087992 ┆ 1220088010 ┆ … ┆ 782.69799 ┆ 1         ┆ true      ┆ 2025-12-0 │
│       ┆ 87467264   ┆ 32917504   ┆ 99382784   ┆   ┆ 8         ┆           ┆           ┆ 3 16:19:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 5.017     │
│ 57    ┆ 1220088017 ┆ 1220088010 ┆ 1220088016 ┆ … ┆ 817.92401 ┆ -1        ┆ false     ┆ 2025-12-0 │
│       ┆ 83058432   ┆ 99382784   ┆ 40448000   ┆   ┆ 1         ┆           ┆           ┆ 3 16:19:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 5.159     │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
trend_manager.pretty_worker_id()

In [ ]:
import polars as pl
import datetime
swing_manager.df_swing.filter(pl.col("id")>=121676756103987200)
display(trend_manager.active_trend_sfs.sfs)

trend_manager.active_trend_sfs.get_fractal_type()
right = trend_manager.active_trend_sfs.sfs[-1]
mid = trend_manager.active_trend_sfs.sfs[-2]
left = trend_manager.active_trend_sfs.sfs[-3]
if left.low_price> mid.low_price and right.low_price > mid.low_price:
    print("ok")

In [ ]:
# 可视化日志
import pandas as pd

df = pd.read_json("./logs/pulao.log", lines=True)
df = df.drop(columns=["logger", "level", "time"])
priority_cols = ["event"]
other_cols = [c for c in df.columns if c not in priority_cols]
df = df[priority_cols + other_cols]
df["info"] = df[other_cols].apply(lambda row: row.dropna().tolist(), axis=1)
df = df.drop(columns=other_cols)
df["info"] = df["info"].apply(lambda x: "" if x == [] else x)
df