In [1]:
from collections import namedtuple
from time import sleep
import logging

from pulao.logging import init_logging

import pandas as pd

from pulao.swing import SwingManager
from pulao.bar import SBar, SBarManager, CBarManager
from vnpy.trader.constant import Exchange, Interval
from vnpy.trader.object import BarData
from pulao.trend import TrendManager

import polars as pl
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pulao.constant import *

from pulao.logging import logger

init_logging(level=logging.DEBUG)
open("./logs/pulao.log", "w").close()  # 每次运行前清空日志
logger.debug("开始运行")

df = pl.read_csv("../dataset/I8888.XDCE_60m.csv", try_parse_dates=True)
df = df.slice(0)  # test

sbar_list = []
columns = df.columns

for idx, row in enumerate(df.iter_rows()):
    row_dict = dict(zip(columns, row))
    # datetime,open,close,high,low,volume,money,open_interest,signal
    datetime = row_dict["datetime"]
    o = row_dict["open"]
    close = row_dict["close"]
    high = row_dict["high"]
    low = row_dict["low"]
    volume = row_dict["volume"]
    money = row_dict["money"]
    open_interest = row_dict["open_interest"]

    bar = BarData(
        gateway_name="ctp-test",
        symbol="i8888",
        exchange=Exchange.SHFE,
        interval=Interval.MINUTE,
        datetime=datetime,
        open_price=o,
        close_price=close,
        high_price=high,
        low_price=low,
        volume=volume,
        open_interest=open_interest,
        turnover=money,
    )
    sbar = SBar(
        symbol=bar.symbol,
        exchange=bar.exchange.value,
        interval=bar.interval.value,
        datetime=datetime,
        turnover=money,
        open_price=o,
        close_price=close,
        high_price=high,
        low_price=low,
        volume=volume,
    )

    sbar_list.append(sbar)
# 模拟行情数据接收
sbar_manager = SBarManager()
cbar_manager = CBarManager(sbar_manager=sbar_manager)
swing_manager = SwingManager(cbar_manager=cbar_manager)
trend_manager = TrendManager(swing_manager=swing_manager)
# 流入模拟数据
for sbar in sbar_list:
    sbar_manager.append(sbar)

logger.debug("运行结束")
# sleep(3) # 等一会，让日志输出完

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"cbar_count": 1, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": null, "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": null, "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"cbar_count": 2, "event": "用于组成分形的cbar数量不够", "level": "warning", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": null, "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"fractal": "Fractal(left=CBar(id=120708060439117824, sbar_start_id=120708060418146304, sbar_end_id=120708060434923520, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 256000), fractal_type=0), middle=CBar(id=120708060455895040, sbar_start_id=120708060455895040, sbar_end_id=120708060455895040, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 260000), fractal_type=-1), right=CBar(id=120708060472672256, sbar_start_id=120708060472672256, sbar_end_id=120708060472672256, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 264000), fractal_type=0))", "event": "首次波段创建", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060489449472, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060472672256, sbar_start_id=120708060455895040, sbar_end_id=120708060472672256, high_price=951.2730102539062, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 268000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060518809600, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060506226688, sbar_start_id=120708060455895040, sbar_end_id=120708060502032384, high_price=955.5689697265625, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 275000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060535586816, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060472672256, sbar_start_id=120708060455895040, sbar_end_id=120708060472672256, high_price=955.5689697265625, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 279000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"event": "_determine_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060560752640, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060543975424, sbar_start_id=120708060455895040, sbar_end_id=120708060543975424, high_price=955.5689697265625, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 285000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060590112768, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060581724160, sbar_start_id=120708060455895040, sbar_end_id=120708060577529856, high_price=955.5689697265625, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 293000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060611084288, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060543975424, sbar_start_id=120708060455895040, sbar_end_id=120708060543975424, high_price=955.5689697265625, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 297000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060632055808, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060619472896, sbar_start_id=120708060455895040, sbar_end_id=120708060619472896, high_price=961.7949829101562, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 302000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060648833024, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060598501376, sbar_start_id=120708060455895040, sbar_end_id=120708060598501376, high_price=961.7949829101562, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 306000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"event": "_determine_swing prev_swing为None，波动率比较取消", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060665610240, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060657221632, sbar_start_id=120708060455895040, sbar_end_id=120708060653027328, high_price=961.7949829101562, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 310000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060686581760, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060673998848, sbar_start_id=120708060455895040, sbar_end_id=120708060673998848, high_price=961.7949829101562, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 315000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060711747584, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060690776064, sbar_start_id=120708060455895040, sbar_end_id=120708060690776064, high_price=961.7949829101562, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 321000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060728524800, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060720136192, sbar_start_id=120708060455895040, sbar_end_id=120708060715941888, high_price=961.7949829101562, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 325000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060745302016, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060736913408, sbar_start_id=120708060455895040, sbar_end_id=120708060732719104, high_price=963.6480102539062, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 329000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060762079232, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060749496320, sbar_start_id=120708060455895040, sbar_end_id=120708060749496320, high_price=974.1920166015625, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 333000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060787245056, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060770467840, sbar_start_id=120708060455895040, sbar_end_id=120708060766273536, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 339000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"start_fractal": "Fractal(left=CBar(id=120708060439117824, sbar_start_id=120708060418146304, sbar_end_id=120708060434923520, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 256000), fractal_type=0), middle=CBar(id=120708060455895040, sbar_start_id=120708060455895040, sbar_end_id=120708060455895040, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 260000), fractal_type=-1), right=CBar(id=120708060472672256, sbar_start_id=120708060472672256, sbar_end_id=120708060472672256, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 264000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120708060749496320, sbar_start_id=120708060749496320, sbar_end_id=120708060749496320, high_price=974.1920166015625, low_price=967.3179931640625, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 330000), fractal_type=0), middle=CBar(id=120708060770467840, sbar_start_id=120708060766273536, sbar_end_id=120708060766273536, high_price=980.2589721679688, low_price=972.8519897460938, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 335000), fractal_type=1), right=CBar(id=120708060791439360, sbar_start_id=120708060791439360, sbar_end_id=120708060791439360, high_price=979.760009765625, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 340000), fractal_type=0))", "active_swing": "Swing(id=120708060787245056, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060770467840, sbar_start_id=120708060455895040, sbar_end_id=120708060766273536, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 339000))", "prev_swing": null, "event": "_determine_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"new_swing": "Swing(id=120708060787245056, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060770467840, sbar_start_id=120708060455895040, sbar_end_id=120708060766273536, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 339000))", "event": "完结波段", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"new_swing": "Swing(id=None, direction=-1, cbar_start_id=120708060770467840, cbar_end_id=120708060791439360, sbar_start_id=120708060766273536, sbar_end_id=120708060791439360, high_price=980.2589721679688, low_price=972.3070068359375, is_completed=False, created_at=None)", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060804022272, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060770467840, sbar_start_id=120708060455895040, sbar_end_id=120708060766273536, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 343000))", "Swing(id=120708060812410880, direction=-1, cbar_start_id=120708060770467840, cbar_end_id=120708060791439360, sbar_start_id=120708060766273536, sbar_end_id=120708060791439360, high_price=980.2589721679688, low_price=972.3070068359375, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 345000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060804022272, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060770467840, sbar_start_id=120708060455895040, sbar_end_id=120708060766273536, high_price=980.2589721679688, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 343000))", "Swing(id=120708060841771008, direction=-1, cbar_start_id=120708060770467840, cbar_end_id=120708060770467840, sbar_start_id=120708060766273536, sbar_end_id=120708060766273536, high_price=980.2589721679688, low_price=972.3070068359375, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 352000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"last_completed_swing": "Swing(id=120708060804022272, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060850159616, sbar_start_id=120708060455895040, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 343000))", "last_bar": "CBar(id=120708060850159616, sbar_start_id=120708060850159616, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=976.85302734375, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 354000), fractal_type=0)", "event": "打开前一完成波段，延续", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060858548224, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060850159616, sbar_start_id=120708060455895040, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 356000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060879519744, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060820799488, sbar_start_id=120708060455895040, sbar_end_id=120708060820799488, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 361000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"start_fractal": "Fractal(left=CBar(id=120708060439117824, sbar_start_id=120708060418146304, sbar_end_id=120708060434923520, high_price=942.2349853515625, low_price=935.9240112304688, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 256000), fractal_type=0), middle=CBar(id=120708060455895040, sbar_start_id=120708060455895040, sbar_end_id=120708060455895040, high_price=939.052001953125, low_price=930.2979736328125, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 260000), fractal_type=-1), right=CBar(id=120708060472672256, sbar_start_id=120708060472672256, sbar_end_id=120708060472672256, high_price=951.2730102539062, low_price=937.4929809570312, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 264000), fractal_type=0))", "end_fractal": "Fractal(left=CBar(id=120708060820799488, sbar_start_id=120708060791439360, sbar_end_id=120708060820799488, high_price=979.7579956054688, low_price=972.3070068359375, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 347000), fractal_type=-1), middle=CBar(id=120708060866936832, sbar_start_id=120708060850159616, sbar_end_id=120708060866936832, high_price=982.2230224609375, low_price=977.7880249023438, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 358000), fractal_type=1), right=CBar(id=120708060883714048, sbar_start_id=120708060883714048, sbar_end_id=120708060883714048, high_price=981.0230102539062, low_price=971.3280029296875, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 362000), fractal_type=0))", "active_swing": "Swing(id=120708060879519744, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060820799488, sbar_start_id=120708060455895040, sbar_end_id=120708060820799488, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 361000))", "prev_swing": null, "event": "_determine_swing 两个分形没有重叠可形成波段", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"new_swing": "Swing(id=120708060879519744, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060866936832, sbar_start_id=120708060455895040, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 361000))", "event": "完结波段", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"new_swing": "Swing(id=None, direction=-1, cbar_start_id=120708060866936832, cbar_end_id=120708060883714048, sbar_start_id=120708060850159616, sbar_end_id=120708060883714048, high_price=982.2230224609375, low_price=971.3280029296875, is_completed=False, created_at=None)", "event": "创建新波段", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060900491264, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060866936832, sbar_start_id=120708060455895040, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 366000))", "Swing(id=120708060908879872, direction=-1, cbar_start_id=120708060866936832, cbar_end_id=120708060883714048, sbar_start_id=120708060850159616, sbar_end_id=120708060883714048, high_price=982.2230224609375, low_price=971.3280029296875, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 368000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060900491264, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060866936832, sbar_start_id=120708060455895040, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 366000))", "Swing(id=120708060946628608, direction=-1, cbar_start_id=120708060866936832, cbar_end_id=120708060866936832, sbar_start_id=120708060850159616, sbar_end_id=120708060866936832, high_price=982.2230224609375, low_price=971.3280029296875, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 377000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060900491264, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060866936832, sbar_start_id=120708060455895040, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 366000))", "Swing(id=120708060980183040, direction=-1, cbar_start_id=120708060866936832, cbar_end_id=120708060950822912, sbar_start_id=120708060850159616, sbar_end_id=120708060950822912, high_price=982.2230224609375, low_price=968.0029907226562, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 385000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}
{"swing_list": ["Swing(id=120708060900491264, direction=1, cbar_start_id=120708060455895040, cbar_end_id=120708060866936832, sbar_start_id=120708060455895040, sbar_end_id=120708060850159616, high_price=982.2230224609375, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 366000))", "Swing(id=120708061001154560, direction=-1, cbar_start_id=120708060866936832, cbar_end_id=120708060988571648, sbar_start_id=120708060850159616, sbar_end_id=120708060984377344, high_price=982.2230224609375, low_price=966.5850219726562, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 2, 10, 44, 390000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 02:10:44"}

AttributeError: 'Pandas' object has no attribute 'cbar_start_id'

In [8]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pulao.constant import *

#
# region . Plotly - Cbar
#
df_cbar = cbar_manager.df_cbar.to_pandas()
df_cbar["datetime"] = pd.date_range("2025-01-01", periods=df_cbar.shape[0], freq="h")
df_cbar["open_price"] = df_cbar["high_price"]
df_cbar["close_price"] = df_cbar["low_price"]
df_cbar.insert(0, "index", range(len(df_cbar)))

# region 构建波段数据
df_swing = swing_manager.df_swing.to_pandas()
df_swing["start_datetime"] = pd.Series(dtype="datetime64[ns]")
df_swing["end_datetime"] = pd.Series(dtype="datetime64[ns]")
df_swing.insert(0, "index", range(len(df_swing)))

for i, row in enumerate(df_swing.itertuples()):
    df = df_cbar[
        (df_cbar["id"] >= row.cbar_start_id) & (df_cbar["id"] <= row.cbar_end_id)
    ]
    start_datetime = df.iloc[0]["datetime"]
    end_datetime = df.iloc[-1]["datetime"]
    df_swing.at[i, "start_datetime"] = start_datetime
    df_swing.at[i, "end_datetime"] = end_datetime

xs_swing = []
ys_swing = []
texts_swing = []
text_positions_swing = []
for i, row in enumerate(df_swing.itertuples()):
    xs_swing += [row.start_datetime, row.end_datetime, None]
    start_index = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["index"].iloc[0]
    end_index = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["index"].iloc[0]
    if row.direction == Direction.UP:
        start_price = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["low_price"].iloc[0]
        end_price = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["high_price"].iloc[0]
        text_positions_swing += ["bottom center", "top center", "middle center"]
    else:
        start_price = df_cbar[(df_cbar["id"] == row.cbar_start_id)]["high_price"].iloc[
            0
        ]
        end_price = df_cbar[(df_cbar["id"] == row.cbar_end_id)]["low_price"].iloc[0]
        text_positions_swing += ["top center", "bottom center", "middle center"]
    ys_swing += [start_price, end_price, None]
    texts_swing += [start_index, end_index, None]
# endregion

# region 构建趋势数据
df_trend = trend_manager.df_trend.to_pandas()
df_trend["start_datetime"] = pd.Series(dtype="datetime64[ns]")
df_trend["end_datetime"] = pd.Series(dtype="datetime64[ns]")
df_trend.insert(0, "index", range(len(df_trend)))

for i, row in enumerate(df_trend.itertuples()):
    df = df_swing[
        (df_swing["id"] >= row.swing_start_id) & (df_swing["id"] <= row.swing_end_id)
    ]
    start_datetime = df.iloc[0]["start_datetime"]
    end_datetime = df.iloc[-1]["end_datetime"]
    df_trend.at[i, "start_datetime"] = start_datetime
    df_trend.at[i, "end_datetime"] = end_datetime

xs_trend = []
ys_trend = []
texts_trend = []
text_positions_trend = []
for i, row in enumerate(df_trend.itertuples()):
    xs_trend += [row.start_datetime, row.end_datetime, None]
    print(row.swing_start_id,df_swing[(df_swing["id"] == row.swing_start_id)])
    start_index = df_swing[(df_swing["id"] == row.swing_start_id)]["index"].iloc[0]
    end_index = df_swing[(df_swing["id"] == row.swing_end_id)]["index"].iloc[0]
    if row.direction == Direction.UP:
        start_price = df_swing[(df_swing["id"] == row.swing_start_id)]["low_price"].iloc[0]
        end_price = df_swing[(df_swing["id"] == row.swing_end_id)]["high_price"].iloc[0]
        text_positions_trend += ["bottom center", "top center", "middle center"]
    else:
        start_price = df_swing[(df_swing["id"] == row.swing_start_id)]["high_price"].iloc[
            0
        ]
        end_price = df_swing[(df_swing["id"] == row.swing_end_id)]["low_price"].iloc[0]
        text_positions_trend += ["top center", "bottom center", "middle center"]
    ys_trend += [start_price, end_price, None]
    texts_trend += [start_index, end_index, None]
# endregion

fig = make_subplots(rows=1, cols=1)
fig.add_trace(
    go.Candlestick(
        x=df_cbar["datetime"],
        open=df_cbar["open_price"],
        high=df_cbar["high_price"],
        low=df_cbar["low_price"],
        close=df_cbar["close_price"],
        name="K线",
    ),
    row=1,
    col=1,
)

df_fractal_bottom = df_cbar[(df_cbar["fractal_type"] == FractalType.BOTTOM)]

fig.add_trace(
    go.Scatter(
        x=df_fractal_bottom["datetime"],
        y=df_fractal_bottom["low_price"] * 0.995,  # 放在K线最低价下方一点，不遮挡蜡烛
        mode="markers+text",
        name="swing point low",
        marker=dict(
            symbol="triangle-up",
            size=14,
            color="#1E90FF",
        ),
        text=df_fractal_bottom["index"],  # ← 添加序号
        textposition="bottom center",  # ← 文字位置
        textfont=dict(size=10, color="white"),
        hovertemplate="<b>波段低点</b><br>"
        + "时间: %{x}<br>"
        + "价格: %{y:.2f}<br>"
        + "<extra></extra>",
    ),
    row=1,
    col=1,
)


df_fractal_top = df_cbar[(df_cbar["fractal_type"] == FractalType.TOP)]

fig.add_trace(
    go.Scatter(
        x=df_fractal_top["datetime"],
        y=df_fractal_top["high_price"] * 1.005,  # 放在K线最高价上方一点
        mode="markers+text",
        name="swing point high",
        marker=dict(
            symbol="triangle-down",
            size=14,
            color="#FF4500",
        ),
        text=df_fractal_top["index"],  # ← 添加序号
        textposition="top center",  # ← 文字位置
        textfont=dict(size=10, color="white"),
        hovertemplate="<b>波段高点</b><br>"
        + "时间: %{x}<br>"
        + "价格: %{y:.2f}<br>"
        + "<extra></extra>",
    ),
    row=1,
    col=1,
)

fig.add_trace(
    go.Scatter(
        x=xs_swing,
        y=ys_swing,
        name="swing segments",
        mode="lines+text",  # lines+text 支持显示文字
        line=dict(width=2, color="orange"),
        text=texts_swing,
        textposition=text_positions_swing,  # 文字位置
    )
)

fig.add_trace(
    go.Scatter(
        x=xs_trend,
        y=ys_trend,
        name="trend segments",
        mode="lines+text",  # lines+text 支持显示文字
        line=dict(width=2, color="red"),
        text=texts_trend,
        textposition=text_positions_trend,  # 文字位置
    )
)

title = "Swing Chart"
fig.update_layout(
    title=title,
    height=900,
    hovermode="x unified",  # X轴悬停联动虚线
)

fig.update_xaxes(
    showgrid=False,
)

fig.update_yaxes(
    showgrid=False,
)

fig.show()

# endregion

120708061961650176    index                  id       cbar_start_id         cbar_end_id  \
1      1  120708061961650176  120708061164732416  120708061923901440

        sbar_start_id         sbar_end_id  high_price   low_price  direction  \
1  120708061126983680  120708061907124224  988.528015  906.143005         -1

   is_completed              created_at start_datetime        end_datetime
1          True 2025-11-30 02:10:44.619     2025-01-02 2025-01-03 04:00:00
120708065853964288    index                  id       cbar_start_id         cbar_end_id  \
8      8  120708065853964288  120708065015103488  120708065820409856

        sbar_start_id         sbar_end_id  high_price   low_price  direction  \
8  120708065015103488  120708065786855424     829.763  748.465027          1

   is_completed              created_at      start_datetime  \
8          True 2025-11-30 02:10:45.547 2025-01-08 10:00:00

         end_datetime
8 2025-01-09 12:00:00
120708066667659264    index                  id       cbar_start_id         cbar_end_id  \
9      9  120708066667659264  120708065820409856  120708066634104832

        sbar_start_id         sbar_end_id  high_price   low_price  direction  \
9  120708065786855424  120708066587967488     829.763  731.429016         -1

   is_completed              created_at      start_datetime  \
9          True 2025-11-30 02:10:45.741 2025-01-09 12:00:00

         end_datetime
9 2025-01-10 13:00:00
120708069133910016     index                  id       cbar_start_id         cbar_end_id  \
10     10  120708069133910016  120708066634104832  120708069083578368

         sbar_start_id         sbar_end_id  high_price   low_price  direction  \
10  120708066587967488  120708069079384064  891.517029  731.429016          1

    is_completed              created_at      start_datetime  \
10          True 2025-11-30 02:10:46.329 2025-01-10 13:00:00

          end_datetime
10 2025-01-14 02:00:00
120708070656442368     index                  id       cbar_start_id         cbar_end_id  \
13     13  120708070656442368  120708069813387264  120708070614499328

         sbar_start_id         sbar_end_id  high_price   low_price  direction  \
13  120708069809192960  120708070610305024  897.002014  852.150024         -1

    is_completed              created_at      start_datetime  \
13          True 2025-11-30 02:10:46.692 2025-01-15 01:00:00

          end_datetime
13 2025-01-16 02:00:00
120708072074117120     index                  id       cbar_start_id         cbar_end_id  \
16     16  120708072074117120  120708071088455680  120708072027979776

         sbar_start_id         sbar_end_id  high_price   low_price  direction  \
16  120708071084261376  120708072023785472  923.666016  847.439026          1

    is_completed              created_at      start_datetime  \
16          True 2025-11-30 02:10:47.030 2025-01-16 15:00:00

          end_datetime
16 2025-01-17 19:00:00
120708072535490560     index                  id       cbar_start_id         cbar_end_id  \
17     17  120708072535490560  120708072027979776  120708072501936128

         sbar_start_id         sbar_end_id  high_price   low_price  direction  \
17  120708072023785472  120708072497741824  923.666016  889.387024         -1

    is_completed              created_at      start_datetime  \
17          True 2025-11-30 02:10:47.140 2025-01-17 19:00:00

          end_datetime
17 2025-01-18 11:00:00
120708077740621824     index                  id       cbar_start_id         cbar_end_id  \
26     26  120708077740621824  120708076109037568  120708077698678784

         sbar_start_id         sbar_end_id  high_price   low_price  direction  \
26  120708076100648960  120708077665124352  863.708984  784.059998          1

    is_completed              created_at      start_datetime  \
26          True 2025-11-30 02:10:48.381 2025-01-22 15:00:00

          end_datetime
26 2025-01-24 07:00:00
120708078692728832     index                  id       cbar_start_id         cbar_end_id  \
27     27  120708078692728832  120708077698678784  120708078629814272

         sbar_start_id         sbar_end_id  high_price   low_price  direction  \
27  120708077665124352  120708078621425664  863.708984  802.969971         -1

    is_completed              created_at      start_datetime  \
27          True 2025-11-30 02:10:48.608 2025-01-24 07:00:00

          end_datetime
27 2025-01-25 03:00:00
120708085747548160 Empty DataFrame
Columns: [index, id, cbar_start_id, cbar_end_id, sbar_start_id, sbar_end_id, high_price, low_price, direction, is_completed, created_at, start_datetime, end_datetime]
Index: []

IndexError: single positional indexer is out-of-bounds

In [14]:
df_swing[df_swing["id"]>120708078692728832]

,index,id,cbar_start_id,cbar_end_id,sbar_start_id,sbar_end_id,high_price,low_price,direction,is_completed,created_at,start_datetime,end_datetime
28,28,120708079237988352,120708078629814272,120708079191851008,120708078621425664,120708079183462400,834.158997,802.969971,1,True,2025-11-30 02:10:48.738,2025-01-25 03:00:00,2025-01-25 15:00:00
29,29,120708081033150464,120708079191851008,120708080978624512,120708079183462400,120708080974430208,834.158997,752.098022,-1,True,2025-11-30 02:10:49.166,2025-01-25 15:00:00,2025-01-27 11:00:00
30,30,120708081377083392,120708080978624512,120708081272225792,120708080974430208,120708081200922624,782.034973,752.098022,1,True,2025-11-30 02:10:49.248,2025-01-27 11:00:00,2025-01-27 17:00:00
31,31,120708081901371392,120708081272225792,120708081851039744,120708081200922624,120708081842651136,782.034973,739.611023,-1,True,2025-11-30 02:10:49.373,2025-01-27 17:00:00,2025-01-28 05:00:00
32,32,120708082727649280,120708081851039744,120708082681511936,120708081842651136,120708082639568896,793.218018,739.611023,1,True,2025-11-30 02:10:49.570,2025-01-28 05:00:00,2025-01-29 00:00:00
33,33,120708084870938624,120708082681511936,120708084828995584,120708082639568896,120708084808024064,793.218018,690.559998,-1,True,2025-11-30 02:10:50.081,2025-01-29 00:00:00,2025-01-31 02:00:00
34,34,120708087161028608,120708084828995584,120708087114891264,120708084808024064,120708087106502656,767.096008,690.559998,1,True,2025-11-30 02:10:50.628,2025-01-31 02:00:00,2025-02-02 08:00:00
35,35,120708088574509056,120708087114891264,120708088524177408,120708087106502656,120708088507400192,767.096008,662.242004,-1,True,2025-11-30 02:10:50.964,2025-02-02 08:00:00,2025-02-03 12:00:00
36,36,120708089610502144,120708088524177408,120708089551781888,120708088507400192,120708089505644544,712.046997,662.242004,1,True,2025-11-30 02:10:51.211,2025-02-03 12:00:00,2025-02-04 14:00:00
37,37,120708089853771776,120708089551781888,120708089799245824,120708089505644544,120708089790857216,712.046997,669.476990,-1,True,2025-11-30 02:10:51.269,2025-02-04 14:00:00,2025-02-04 20:00:00
38,38,120708090206093312,120708089799245824,120708090155761664,120708089790857216,120708090147373056,702.216980,669.476990,1,True,2025-11-30 02:10:51.353,2025-02-04 20:00:00,2025-02-05 02:00:00
39,39,120708090646495232,120708090155761664,120708090583580672,120708090147373056,120708090575192064,702.216980,657.408020,-1,True,2025-11-30 02:10:51.458,2025-02-05 02:00:00,2025-02-05 10:00:00
40,40,120708091829288960,120708090583580672,120708091770568704,120708090575192064,120708091757985792,842.429993,657.408020,1,True,2025-11-30 02:10:51.740,2025-02-05 10:00:00,2025-02-06 12:00:00
41,41,120708095243452416,120708091770568704,120708095180537856,120708091757985792,120708095172149248,842.429993,737.958984,-1,True,2025-11-30 02:10:52.554,2025-02-06 12:00:00,2025-02-08 20:00:00
42,42,120708098041053184,120708095180537856,120708097986527232,120708095172149248,120708097973944320,798.085022,737.958984,1,True,2025-11-30 02:10:53.221,2025-02-08 20:00:00,2025-02-11 04:00:00
43,43,120708099735552000,120708097986527232,120708099668443136,120708097973944320,120708099655860224,798.085022,732.270996,-1,True,2025-11-30 02:10:53.625,2025-02-11 04:00:00,2025-02-12 10:00:00
44,44,120708103162298368,120708099668443136,120708103099383808,120708099655860224,120708103082606592,807.202026,732.270996,1,True,2025-11-30 02:10:54.442,2025-02-12 10:00:00,2025-02-15 10:00:00
45,45,120708103724335104,120708103099383808,120708103661420544,120708103082606592,120708103611088896,807.202026,776.815979,-1,True,2025-11-30 02:10:54.576,2025-02-15 10:00:00,2025-02-15 22:00:00
46,46,120708104437366784,120708103661420544,120708104374452224,120708103611088896,120708104319926272,823.898987,776.815979,1,True,2025-11-30 02:10:54.746,2025-02-15 22:00:00,2025-02-16 10:00:00
47,47,120708104827437056,120708104374452224,120708104764522496,120708104319926272,120708104747745280,823.898987,796.780029,-1,True,2025-11-30 02:10:54.839,2025-02-16 10:00:00,2025-02-16 16:00:00
48,48,120708105137815552,120708104764522496,120708105070706688,120708104747745280,120708105058123776,813.625977,796.780029,1,True,2025-11-30 02:10:54.913,2025-02-16 16:00:00,2025-02-16 23:00:00
49,49,120708107113332736,120708105070706688,120708107033640960,120708105058123776,120708107021058048,813.625977,763.943970,-1,True,2025-11-30 02:10:55.384,2025-02-16 23:00:00,2025-02-18 08:00:00
50,50,120708108409372672,120708107033640960,120708108333875200,120708107021058048,120708108321292288,786.497009,763.943970,1,True,2025-11-30 02:10:55.693,2025-02-18 08:00:00,2025-02-19 04:00:00
51,51,120708108933660672,120708108333875200,120708108849774592,120708108321292288,120708108832997376,786.497009,758.200989,-1,True,2025-11-30 02:10:55.818,2025-02-19 04:00:00,2025-02-19 12:00:00
52,52,120708109688635392,120708108849774592,120708109617332224,120708108832997376,120708109604749312,786.112000,758.200989,1,True,2025-11-30 02:10:55.998,2025-02-19 12:00:00,2025-02-20 00:00:00
53,53,120708111299248128,120708109617332224,120708111236333568,120708109604749312,120708111215362048,786.112000,741.731995,-1,True,2025-11-30 02:10:56.382,2025-02-20 00:00:00,2025-02-21 04:00:00
54,54,120708116869283840,120708111236333568,120708116802174976,120708111215362048,120708116777009152,824.000977,741.731995,1,True,2025-11-30 02:10:57.710,2025-02-21 04:00:00,2025-02-24 07:00:00
55,55,120708118282764288,120708116802174976,120708118089826304,120708116777009152,120708117938831360,824.000977,782.697998,-1,True,2025-11-30 02:10:58.047,2025-02-24 07:00:00,2025-02-25 04:00:00
56,56,120708119675273216,120708118089826304,120708119603970048,120708117938831360,120708119545249792,835.335022,782.697998,1,True,2025-11-30 02:10:58.379,2025-02-25 04:00:00,2025-02-26 04:00:00
57,57,120708120136646656,120708119603970048,120708120023400448,120708119545249792,120708120002428928,835.335022,817.924011,-1,False,2025-11-30 02:10:58.489,2025-02-26 04:00:00,2025-02-26 07:00:00

In [1]:
from typing import List

# 测试swing 构建算法
from IPython.display import display
from pulao.logging import logger, init_logging
import logging
from time import sleep
from pulao.swing import Swing, SwingManager
from pulao.trend import Trend, TrendManager
from pulao.bar import CBar, CBarManager, SBarManager
from pulao.constant import *

init_logging(level=logging.DEBUG)
with open("./logs/pulao.log", "w"):
    pass  # 每次运行前清空日志

logger.debug("开始运行")


def format_df_trend():
    import polars as pl

    if "index" in swing_manager.df_swing.columns:
        swing_manager.df_swing = swing_manager.df_swing.drop("index")
    swing_manager.df_swing = swing_manager.df_swing.with_row_index("index")

    df_swing_tmp = swing_manager.df_swing.select(["id", "index"])
    df1 = trend_manager.df_trend.join(
        df_swing_tmp, left_on="swing_start_id", right_on="id", how="left"
    )
    df2 = trend_manager.df_trend.join(
        df_swing_tmp, left_on="swing_end_id", right_on="id", how="left"
    )
    df1 = df1.rename({"index": "swing_start_index"})
    df2 = df2.rename({"index": "swing_end_index"})
    df2 = df2.select(["id", "swing_end_index"])
    df1 = df1.join(df2, on="id", how="left")
    df = df1.select(
        [
            "id",
            "swing_start_index",
            "swing_end_index",
            "swing_start_id",
            "swing_end_id",
            "high_price",
            "low_price",
            "direction",
            "is_completed",
            "created_at",
        ]
    )

    return df


cbar_manager = CBarManager(sbar_manager=SBarManager())
swing_manager = SwingManager(cbar_manager=cbar_manager)
trend_manager = TrendManager(swing_manager=swing_manager)
df_cbar = cbar_manager.read_parquet()
df_swing = swing_manager.read_parquet()
swing_manager.df_swing = swing_manager.df_swing.slice(0, 0)  # 清空原数据
for i in range(df_swing.height - 1):
    swing = Swing(**df_swing.row(i, named=True))
    swing_manager._append_swing(swing)
    swing_manager.notify(EventType.SWING_CHANGED)


logger.debug("运行结束")
sleep(0.2)


display("df_trend")
df = format_df_trend()
display(df)

display("df_swing")
swing_manager.df_swing

{"event": "开始运行", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"swing_list": ["Swing(id=120703444741783552, direction=1, cbar_start_id=120691400458108928, cbar_end_id=120691400957231104, sbar_start_id=120691400458108928, sbar_end_id=120691400898510848, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 788000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"swing_list": ["Swing(id=120703444741783552, direction=1, cbar_start_id=120691400458108928, cbar_end_id=120691400957231104, sbar_start_id=120691400458108928, sbar_end_id=120691400898510848, high_price=988.5280151367188, low_price=930.2979736328125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 788000))", "Swing(id=120703444750172160, direction=-1, cbar_start_id=120691400957231104, cbar_end_id=120691401749954560, sbar_start_id=120691400898510848, sbar_end_id=120691401733177344, high_price=988.5280151367188, low_price=906.1430053710938, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 790000))"], "event": "波段数量不足3个，跳过", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"new_trend": "Trend(id=None, direction=-1, swing_start_id=120703444750172160, swing_end_id=120703444779532288, high_price=955.9249877929688, low_price=906.1430053710938, sbar_start_id=120691400898510848, sbar_end_id=120691403138269184, is_completed=False, created_at=None)", "event": "首次创建趋势", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703444817281024, direction=-1, swing_start_id=120703444750172160, swing_end_id=120703444813086721, high_price=955.9249877929688, low_price=731.4290161132812, sbar_start_id=120691400898510848, sbar_end_id=120691406082670592, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 806000))", "sfs": ["Swing(id=120703444771143680, direction=1, cbar_start_id=120691401749954560, cbar_end_id=120691402085498880, sbar_start_id=120691401733177344, sbar_end_id=120691402085498880, high_price=955.9249877929688, low_price=906.1430053710938, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 795000))", "Swing(id=120703444787920896, direction=1, cbar_start_id=120691403138269184, cbar_end_id=120691403230543872, sbar_start_id=120691403138269184, sbar_end_id=120691403230543872, high_price=879.8569946289062, low_price=842.1339721679688, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 799000))", "Swing(id=120703444804698112, direction=1, cbar_start_id=120691403616419840, cbar_end_id=120691403981324288, sbar_start_id=120691403612225536, sbar_end_id=120691403956158464, high_price=873.1190185546875, low_price=834.3880004882812, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 803000))"], "event": "特征序列发现包含关系", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703444842446848, direction=-1, swing_start_id=120703444750172160, swing_end_id=120703444821475328, high_price=955.9249877929688, low_price=731.4290161132812, sbar_start_id=120691400898510848, sbar_end_id=120691408754442240, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 812000))", "sfs": ["Swing(id=120703444771143680, direction=1, cbar_start_id=120691401749954560, cbar_end_id=120691402085498880, sbar_start_id=120691401733177344, sbar_end_id=120691402085498880, high_price=955.9249877929688, low_price=906.1430053710938, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 795000))", "Swing(id=120703444787920896, direction=1, cbar_start_id=120691403138269184, cbar_end_id=120691403230543872, sbar_start_id=120691403138269184, sbar_end_id=120691403230543872, high_price=879.8569946289062, low_price=842.1339721679688, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 799000))", "Swing(id=120703444804698112, direction=1, cbar_start_id=120691403616419840, cbar_end_id=120691403981324288, sbar_start_id=120691403612225536, sbar_end_id=120691403956158464, high_price=873.1190185546875, low_price=834.3880004882812, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 803000))", "Swing(id=120703444817281024, direction=1, cbar_start_id=120691406120419328, cbar_end_id=120691408259514368, sbar_start_id=120691406082670592, sbar_end_id=120691408255320064, high_price=829.7630004882812, low_price=731.4290161132812, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 806000))", "Swing(id=120703444842446848, direction=1, cbar_start_id=120691408758636544, cbar_end_id=120691408905437184, sbar_start_id=120691408754442240, sbar_end_id=120691408901242880, high_price=897.0020141601562, low_price=857.7769775390625, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 812000))"], "event": "特征序列发现包含关系", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703444842446848, direction=-1, swing_start_id=120703444750172160, swing_end_id=120703444813086721, high_price=955.9249877929688, low_price=731.4290161132812, sbar_start_id=120691400898510848, sbar_end_id=120691406082670592, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 812000))", "event": "趋势终止", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"new_trend": "Trend(id=None, direction=1, swing_start_id=120703444817281024, swing_end_id=120703444859224064, high_price=910.8989868164062, low_price=731.4290161132812, sbar_start_id=120691406082670592, sbar_end_id=120691411363299328, is_completed=False, created_at=None)", "last_swing": "Swing(id=120703444859224064, direction=1, cbar_start_id=120691411271024640, cbar_end_id=120691411388465152, sbar_start_id=120691411266830336, sbar_end_id=120691411363299328, high_price=910.8989868164062, low_price=889.3870239257812, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 816000))", "event": "创建新趋势", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703444913750016, direction=1, swing_start_id=120703444817281024, swing_end_id=120703444905361408, high_price=910.8989868164062, low_price=731.4290161132812, sbar_start_id=120691406082670592, sbar_end_id=120691413485617152, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 829000))", "sfs": ["Swing(id=120703444876001280, direction=-1, cbar_start_id=120691411388465152, cbar_end_id=120691412462206976, sbar_start_id=120691411363299328, sbar_end_id=120691412453818368, high_price=910.8989868164062, low_price=820.2650146484375, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 820000))"], "event": "特征序列发现包含关系", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703444947304448, direction=1, swing_start_id=120703444817281024, swing_end_id=120703444855029760, high_price=923.666015625, low_price=731.4290161132812, sbar_start_id=120691406082670592, sbar_end_id=120691410822234112, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 837000))", "event": "趋势终止", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"new_trend": "Trend(id=None, direction=-1, swing_start_id=120703444855029761, swing_end_id=120703444947304448, high_price=923.666015625, low_price=802.969970703125, sbar_start_id=120691410822234112, sbar_end_id=120691417092718592, is_completed=False, created_at=None)", "last_swing": "Swing(id=120703444947304448, direction=-1, cbar_start_id=120691416400658432, cbar_end_id=120691417105301504, sbar_start_id=120691416362909696, sbar_end_id=120691417092718592, high_price=863.708984375, low_price=802.969970703125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 837000))", "event": "创建新趋势", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703444997636097, direction=-1, swing_start_id=120703444855029761, swing_end_id=120703444997636096, high_price=923.666015625, low_price=739.6110229492188, sbar_start_id=120691410822234112, sbar_end_id=120691419915485184, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 849000))", "sfs": ["Swing(id=120703444955693056, direction=1, cbar_start_id=120691417105301504, cbar_end_id=120691417558286336, sbar_start_id=120691417092718592, sbar_end_id=120691417554092032, high_price=834.1589965820312, low_price=802.969970703125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 839000))"], "event": "特征序列发现包含关系", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703445026996224, direction=-1, swing_start_id=120703444855029761, swing_end_id=120703445022801921, high_price=923.666015625, low_price=662.2420043945312, sbar_start_id=120691410822234112, sbar_end_id=120691427234545664, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 856000))", "sfs": ["Swing(id=120703444955693056, direction=1, cbar_start_id=120691417105301504, cbar_end_id=120691417558286336, sbar_start_id=120691417092718592, sbar_end_id=120691417554092032, high_price=834.1589965820312, low_price=802.969970703125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 839000))", "Swing(id=120703445001830400, direction=1, cbar_start_id=120691419923873792, cbar_end_id=120691420670459904, sbar_start_id=120691419915485184, sbar_end_id=120691420632711168, high_price=782.0349731445312, low_price=739.6110229492188, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 850000))", "Swing(id=120703445014413312, direction=1, cbar_start_id=120691422675337216, cbar_end_id=120691424797655040, sbar_start_id=120691422666948608, sbar_end_id=120691424789266432, high_price=767.0960083007812, low_price=690.5599975585938, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 853000))"], "event": "特征序列发现包含关系", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703445047967744, direction=-1, swing_start_id=120703444855029761, swing_end_id=120703445031190528, high_price=923.666015625, low_price=657.4080200195312, sbar_start_id=120691410822234112, sbar_end_id=120691428010491904, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 861000))", "sfs": ["Swing(id=120703444955693056, direction=1, cbar_start_id=120691417105301504, cbar_end_id=120691417558286336, sbar_start_id=120691417092718592, sbar_end_id=120691417554092032, high_price=834.1589965820312, low_price=802.969970703125, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 839000))", "Swing(id=120703445001830400, direction=1, cbar_start_id=120691419923873792, cbar_end_id=120691420670459904, sbar_start_id=120691419915485184, sbar_end_id=120691420632711168, high_price=782.0349731445312, low_price=739.6110229492188, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 850000))", "Swing(id=120703445014413312, direction=1, cbar_start_id=120691422675337216, cbar_end_id=120691424797655040, sbar_start_id=120691422666948608, sbar_end_id=120691424789266432, high_price=767.0960083007812, low_price=690.5599975585938, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 853000))"], "event": "特征序列发现包含关系", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703445060550656, direction=-1, swing_start_id=120703444855029761, swing_end_id=120703445031190528, high_price=923.666015625, low_price=657.4080200195312, sbar_start_id=120691410822234112, sbar_end_id=120691428010491904, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 864000))", "event": "趋势终止", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"new_trend": "Trend(id=None, direction=1, swing_start_id=120703445047967744, swing_end_id=120703445060550656, high_price=798.0850219726562, low_price=657.4080200195312, sbar_start_id=120691428010491904, sbar_end_id=120691435023368192, is_completed=False, created_at=None)", "last_swing": "Swing(id=120703445060550656, direction=1, cbar_start_id=120691432452259840, cbar_end_id=120691435035951104, sbar_start_id=120691432443871232, sbar_end_id=120691435023368192, high_price=798.0850219726562, low_price=737.958984375, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 864000))", "event": "创建新趋势", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703445119270912, direction=1, swing_start_id=120703445047967744, swing_end_id=120703445047967744, high_price=842.4299926757812, low_price=657.4080200195312, sbar_start_id=120691428010491904, sbar_end_id=120691429210062848, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 878000))", "event": "趋势终止", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"new_trend": "Trend(id=None, direction=-1, swing_start_id=120703445056356352, swing_end_id=120703445119270912, high_price=842.4299926757812, low_price=763.9439697265625, sbar_start_id=120691429210062848, sbar_end_id=120691444758347776, is_completed=False, created_at=None)", "last_swing": "Swing(id=120703445119270912, direction=-1, cbar_start_id=120691442560532480, cbar_end_id=120691444770930688, sbar_start_id=120691442547949568, sbar_end_id=120691444758347776, high_price=813.6259765625, low_price=763.9439697265625, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 878000))", "event": "创建新趋势", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703445152825345, direction=-1, swing_start_id=120703445056356352, swing_end_id=120703445152825344, high_price=842.4299926757812, low_price=741.7319946289062, sbar_start_id=120691429210062848, sbar_end_id=120691449091063808, is_completed=False, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 886000))", "sfs": ["Swing(id=120703445131853824, direction=1, cbar_start_id=120691444770930688, cbar_end_id=120691446008250368, sbar_start_id=120691444758347776, sbar_end_id=120691445991473152, high_price=786.4970092773438, low_price=763.9439697265625, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 881000))"], "event": "特征序列发现包含关系", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"active_trend": "Trend(id=120703445161213952, direction=-1, swing_start_id=120703445056356352, swing_end_id=120703445077327872, high_price=842.4299926757812, low_price=732.27099609375, sbar_start_id=120691429210062848, sbar_end_id=120691436558483456, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 888000))", "event": "趋势终止", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"new_trend": "Trend(id=None, direction=1, swing_start_id=120703445081522176, swing_end_id=120703445165408256, high_price=835.3350219726562, low_price=732.27099609375, sbar_start_id=120691436558483456, sbar_end_id=120691456699531264, is_completed=False, created_at=None)", "last_swing": "Swing(id=120703445165408256, direction=1, cbar_start_id=120691455483183104, cbar_end_id=120691456758251520, sbar_start_id=120691455315410944, sbar_end_id=120691456699531264, high_price=835.3350219726562, low_price=782.697998046875, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 52, 23, 889000))", "event": "创建新趋势", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}
{"event": "运行结束", "level": "debug", "logger": "__main__", "time": "2025-11-30 01:52:23"}

'df_trend'

shape: (6, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ swing_sta ┆ swing_end ┆ swing_sta ┆ … ┆ low_price ┆ direction ┆ is_comple ┆ created_ │
│ ---       ┆ rt_index  ┆ _index    ┆ rt_id     ┆   ┆ ---       ┆ ---       ┆ ted       ┆ at       │
│ u64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f32       ┆ i8        ┆ ---       ┆ ---      │
│           ┆ u32       ┆ u32       ┆ u64       ┆   ┆           ┆           ┆ bool      ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [ms]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 120703444 ┆ 1         ┆ 9         ┆ 120703444 ┆ … ┆ 731.42901 ┆ -1        ┆ true      ┆ 2025-11- │
│ 871806976 ┆           ┆           ┆ 750172160 ┆   ┆ 6         ┆           ┆           ┆ 30 01:52 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :23.819  │
│ 120703444 ┆ 10        ┆ 16        ┆ 120703444 ┆ … ┆ 731.42901 ┆ 1         ┆ true      ┆ 2025-11- │
│ 951498752 ┆           ┆           ┆ 817281024 ┆   ┆ 6         ┆           ┆           ┆ 30 01:52 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :23.838  │
│ 120703445 ┆ 17        ┆ 39        ┆ 120703444 ┆ … ┆ 657.40802 ┆ -1        ┆ true      ┆ 2025-11- │
│ 073133568 ┆           ┆           ┆ 855029761 ┆   ┆           ┆           ┆           ┆ 30 01:52 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :23.867  │
│ 120703445 ┆ 40        ┆ 40        ┆ 120703445 ┆ … ┆ 657.40802 ┆ 1         ┆ true      ┆ 2025-11- │
│ 127659520 ┆           ┆           ┆ 047967744 ┆   ┆           ┆           ┆           ┆ 30 01:52 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :23.880  │
│ 120703445 ┆ 41        ┆ 43        ┆ 120703445 ┆ … ┆ 732.27099 ┆ -1        ┆ true      ┆ 2025-11- │
│ 169602560 ┆           ┆           ┆ 056356352 ┆   ┆ 6         ┆           ┆           ┆ 30 01:52 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :23.890  │
│ 120703445 ┆ 44        ┆ 56        ┆ 120703445 ┆ … ┆ 732.27099 ┆ 1         ┆ false     ┆ 2025-11- │
│ 173796864 ┆           ┆           ┆ 081522176 ┆   ┆ 6         ┆           ┆           ┆ 30 01:52 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :23.891  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

'df_swing'

shape: (57, 11)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ index ┆ id         ┆ cbar_start ┆ cbar_end_i ┆ … ┆ low_price ┆ direction ┆ is_comple ┆ created_a │
│ ---   ┆ ---        ┆ _id        ┆ d          ┆   ┆ ---       ┆ ---       ┆ ted       ┆ t         │
│ u32   ┆ u64        ┆ ---        ┆ ---        ┆   ┆ f32       ┆ i8        ┆ ---       ┆ ---       │
│       ┆            ┆ u64        ┆ u64        ┆   ┆           ┆           ┆ bool      ┆ datetime[ │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ ms]       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0     ┆ 1207034447 ┆ 1206914004 ┆ 1206914009 ┆ … ┆ 930.29797 ┆ 1         ┆ true      ┆ 2025-11-3 │
│       ┆ 41783552   ┆ 58108928   ┆ 57231104   ┆   ┆ 4         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.788     │
│ 1     ┆ 1207034447 ┆ 1206914009 ┆ 1206914017 ┆ … ┆ 906.14300 ┆ -1        ┆ true      ┆ 2025-11-3 │
│       ┆ 50172160   ┆ 57231104   ┆ 49954560   ┆   ┆ 5         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.790     │
│ 2     ┆ 1207034447 ┆ 1206914017 ┆ 1206914020 ┆ … ┆ 906.14300 ┆ 1         ┆ true      ┆ 2025-11-3 │
│       ┆ 71143680   ┆ 49954560   ┆ 85498880   ┆   ┆ 5         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.795     │
│ 3     ┆ 1207034447 ┆ 1206914020 ┆ 1206914031 ┆ … ┆ 842.13397 ┆ -1        ┆ true      ┆ 2025-11-3 │
│       ┆ 79532288   ┆ 85498880   ┆ 38269184   ┆   ┆ 2         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.797     │
│ 4     ┆ 1207034447 ┆ 1206914031 ┆ 1206914032 ┆ … ┆ 842.13397 ┆ 1         ┆ true      ┆ 2025-11-3 │
│       ┆ 87920896   ┆ 38269184   ┆ 30543872   ┆   ┆ 2         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.799     │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 52    ┆ 1207034451 ┆ 1206914465 ┆ 1206914473 ┆ … ┆ 758.20098 ┆ 1         ┆ true      ┆ 2025-11-3 │
│       ┆ 48631040   ┆ 57704192   ┆ 67204864   ┆   ┆ 9         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.885     │
│ 53    ┆ 1207034451 ┆ 1206914473 ┆ 1206914491 ┆ … ┆ 741.73199 ┆ -1        ┆ true      ┆ 2025-11-3 │
│       ┆ 52825344   ┆ 67204864   ┆ 16229632   ┆   ┆ 5         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.886     │
│ 54    ┆ 1207034451 ┆ 1206914491 ┆ 1206914542 ┆ … ┆ 741.73199 ┆ 1         ┆ true      ┆ 2025-11-3 │
│       ┆ 52825345   ┆ 16229632   ┆ 33280512   ┆   ┆ 5         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.886     │
│ 55    ┆ 1207034451 ┆ 1206914542 ┆ 1206914554 ┆ … ┆ 782.69799 ┆ -1        ┆ true      ┆ 2025-11-3 │
│       ┆ 57019648   ┆ 33280512   ┆ 83183104   ┆   ┆ 8         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.887     │
│ 56    ┆ 1207034451 ┆ 1206914554 ┆ 1206914567 ┆ … ┆ 782.69799 ┆ 1         ┆ true      ┆ 2025-11-3 │
│       ┆ 65408256   ┆ 83183104   ┆ 58251520   ┆   ┆ 8         ┆           ┆           ┆ 0 01:52:2 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 3.889     │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
swing_manager.df_swing = swing_manager.df_swing.drop("index")
swing_manager.next_swing(120701055628476416)

Swing(id=120701055628476416, direction=-1, cbar_start_id=120691405457719296, cbar_end_id=120691406120419328, sbar_start_id=120691405440942080, sbar_end_id=120691406082670592, high_price=829.7630004882812, low_price=731.4290161132812, is_completed=True, created_at=datetime.datetime(2025, 11, 30, 1, 42, 54, 179000))

In [ ]:
# 可视化日志
import pandas as pd

df = pd.read_json("./logs/pulao.log", lines=True)
df = df.drop(columns=["logger", "level", "time"])
priority_cols = ["event"]
other_cols = [c for c in df.columns if c not in priority_cols]
df = df[priority_cols + other_cols]
df["info"] = df[other_cols].apply(lambda row: row.dropna().tolist(), axis=1)
df = df.drop(columns=other_cols)
df["info"] = df["info"].apply(lambda x: "" if x == [] else x)
df

In [ ]:
cbar_manager.read_parquet()